### ISSUE TITLE
rosbag2 compilation stuck in zstd_vendor node does not move

### ISSUE THREAD

**Issue by yunerJin** [ros2/rosbag2#1035]
## Description
** When I compile rosbag2, the progress compilation is stuck in the zstd_vendor node **

![选区_021](https://user-images.githubusercontent.com/55445755/176160160-bb5c4e70-6214-4ed2-9c05-b0ad19f695d0.png)

How to solve this problem!

## System (please complete the following information)
 - OS: Docker(Ubuntu 20.04)
 - ROS 2 Distro: Foxy
 - Version: foxy branch

**Comment by MichaelOrlov** [comment]
@yunerJin Do you have access to the internet on machine where you are running build? 
It might be intermittent problem with access to the zstd third party dependencies when trying to pull it out via internet during the build.

**Comment by MichaelOrlov** [comment]
Closing as stale and not reproducible issue.
