### ISSUE TITLE
writer_choices: set object is not subscriptable

### ISSUE THREAD

**Issue by EsipovPA** [ros2/rosbag2#1043]
## Description
The [definition of the get_registered_writers function](https://github.com/ros2/rosbag2/blob/rolling/rosbag2_py/src/rosbag2_py/_writer.cpp#L83) specifies the return type of the function to be std::unordered_set. As a result, if there is no 'sqlite3' writer choice in the set of writer_choices, one will get an exception like this:
```
default_writer = 'sqlite3' if 'sqlite3' in writer_choices else writer_choices[0]
TypeError: 'set' object is not subscriptable
```
The exception is caused by [this string](https://github.com/ros2/rosbag2/blob/rolling/ros2bag/ros2bag/verb/record.py#L38) in ros2bag/ros2bag/verb/record.py

### Expected Behavior
Looks like in this case the default_writer is expected to have any value, that is in the beginning of the writer_choices list.

### Actual Behavior
The above exception is thrown

## To Reproduce
1. Run 'ros2 bag record' on a system with no sqlite3 installed

## System (please complete the following information)
 - OS: Ubuntu 20.04 (Focal Fossa)
 - ROS 2 Distro: Galactic

## A possible solution
I took the liberty of offering a solution to the problem described in [this PR](https://github.com/ros2/rosbag2/pull/1044).

**Comment by MichaelOrlov** [comment]
Closing as done in #1044
