### ISSUE TITLE
tf_static doesnt work with rosbag2 but tf does

### ISSUE THREAD

**Issue by saippua** [ros2/rosbag2#1049]
## Description
I'm saving a rosbag2 with `ros2 bag record -a`, playing it back and viewing it in rviz2.
I'm publishing a pose and a transformation. the transformation is static (it doesnt change)

### Expected Behavior
When I playback the rosbag2, I should be able to see the transformation in rviz2.

### Actual Behavior
* if I publish the transformation using `StaticTransformBroadcaster` (once at the beginning of the recording), the transformation does not appear in rviz2 when I play the bag. I've checked that the bag file has the `/tf_static` topic and there is a message there.
* If I publish the transformation using `TransformBroadcaster`, the transformation *does* appear in rviz2, and I see the tf tree correctly.
* If I run rviz2 while publishing to visualize the data feed directly without using rosbag2 in the middle, both `StaticTransformBroadcaster` and `TransformBroadcaster` work.

## To Reproduce
1. run a publisher that publishes a pose and transformation
2. record it using `ros2 bag record -a`
3. play back the recording `ros2 bag play -l <bag>`
4. view result in rviz2. If using `StaticTransformBroadcaster`, the tf wont be in rviz.

## System (please complete the following information)
 - OS: Ubuntu 20.04
 - ROS 2 Distro: Galactic
 - Version: rosbag2 0.9.1

## Additional information
I'm publishing the transformation twice when recording the bag. The first publish allows the recorder to discover and subscribe to the topic, but it doesnt actually record a message. I publish again to make sure a message is recorded. For all tests I'm also making sure that there are `tf` or `tf_static` messages in the bag files I'm playing.

**Comment by MichaelOrlov** [comment]
@saippua Can you please provide example of the rosbag2 with messages from `StaticTransformBroadcaster` which are not displaying in rviz?

**Comment by bjajoh** [comment]
I have exactly the same issue, static tf transforms are not being able to be visualized with rviz.

**Comment by MichaelOrlov** [comment]
@saippua @bjajoh We need reliable  reproducer for this issue. 
Could you please provide recorded bags with `StaticTransformBroadcaster` and with `TransformBroadcaster` to be able to reproduce and debug issue or please provide minimum valuable reproducer for `item 1`.
> 1. run a publisher that publishes a pose and transformation

**Comment by FlorianPix** [comment]
I have the same issue. 
[Heres how the tf tree should look like.](https://github.com/ros2/rosbag2/files/10741533/normal.pdf)
[Here's how it looks when replaying the ros2 bag.](https://github.com/ros2/rosbag2/files/10741535/ros2_bag.pdf)

**Comment by Alex-Beh** [comment]
Hello, I am facing the same issue on ROS2 foxy. Will try to debug and report back if there is any findings.

**Update:** But I cannot duplicate the issue on ROS2 humble.

@FlorianPix May I know your ROS2 distro? Have you solved your issue?

**Comment by MichaelOrlov** [comment]
- Closing as a stale issue.

**Comment by kameel2311** [comment]
I would like to reopen this issue as I have a bag file that contains tf_static

Playing the bag file with custom qos override to ensure that topics is being published as transient local is not fixing the issue.
The metadata file shows that the topic does indeed have messages

Issue encountered with following ROS versions: Iron & Jazzy

**Comment by tjsos** [comment]
Hi @kameel2311 

What I have experienced is that, if your bag doesn't have `/tf_static` information to begin with, then you can't bring it back. The bags are a time-series data-structure. StaticTransformBroadcaster saves those transforms into the buffer of the DDS. However what I tried was to record the bag with qos override for `/tf_static`, then you are guaranteed to have all the static transforms recorded inside the bag.
This is my understanding: anything published to `/tf_static` is assumed to be latching and having transient QoS.
Transient QoS means it will be stored to the buffer of the DDS and doesnt exist as a topic/msg unless some node asks it to be. `ros2 bag` by default only look for Volatile QoS i.e only newer msgs. But we can change the QoS policy for /tf_static during recording time such that it will look for transient QoS also i.e new and old msgs.

Further reading: https://docs.ros.org/en/rolling/Concepts/Intermediate/About-Quality-of-Service-Settings.html

Steps to recreate:

1.  Create a yaml file with the following QoS override for /tf_static
```
/tf_static:
  depth: 1
  durability: transient_local
  history: keep_last
  reliability: reliable
```

2.  `ros2 bag record -a --qos-profile-overrides-path <path_of_yaml_file>`

  3, See if you are able to have all the static transforms in the bag
