### ISSUE TITLE
Read ros2 bag with MCAP format

### ISSUE THREAD

**Issue by fnobis** [ros2/rosbag2#1070]
I try to read a rosbag following this example:

https://github.com/ros2/rosbag2/blob/master/rosbag2_py/test/test_sequential_reader.py

In the file `from common import get_rosbag_options` is executed. This is needed in order to load a ros2 bag. 
However, I do not see how I get the dependencies common to execute the package. I cannot find this on pypi.

Also if there is any further guide on how to use the api would be helpful. 

I am using a MCAP bag file.

**Comment by laurafbec** [comment]
Hi @fnobis!
Did you solve the problem? I'm getting the error ImportError: cannot import name 'get_rosbag_options' from 'common' (/home/laura/.local/lib/python3.8/site-packages/common/__init__.py)
Thanks
