### ISSUE TITLE
Add a benchmark fixture to compare raw write throughput for different plugins

### ISSUE THREAD

**Issue by james-rms** [ros2/rosbag2#1092]
## Description

We need a way to assess write throughput of the MCAP storage plugin against the default SQLite plugin at a lower level, without bringing in the SequentialWriter or other pub/sub infrastructure.

### Desirable metrics
* How many messages can we write per second?
* How many bytes can we write per second?
* How much memory is used for a given write call?
  * How many heap allocations? how large?
* How large are the resulting files?

### Configurations dimensions to test across
* Message size distribution
  * All large
  * All small
  * Mixed large and small (sample from representative dataset ie. nuScenes)
* storage plugin
  * MCAP, SQLite (default)
* Compression configuration
  * File-level
  * message-level
  * Chunk-level (MCAP only)
* Plugin-specific configuration values
  * MCAP:
    * Message index on/off
    * CRC on/off
    * Chunking on/off
  * SQLite
    * Resilient vs. Optimized

## Related Issues

** Is this feature dependent on any other features? Is it part of a larger project? Note here. **

## Completion Criteria

** What needs to be true before we can call this "Done"? Bullet lists are appropriate. **

## Implementation Notes / Suggestions

* I'm not sure if anyone has made this work before using ROS build infrastructure, but one way to profile memory would be to use [https://gperftools.github.io/gperftools/heapprofile.html]

## Testing Notes / Suggestions

(covered above)
** All features in this project need tests. Please give some input on cases that will need to be tested - and how the testing might be implemented. **

**Comment by MichaelOrlov** [comment]
- Closing this issue as a stale and wouldn't be done. Please refer to the closing comment in the #1106
