### ISSUE TITLE
Exclude/include topics by type

### ISSUE THREAD

**Issue by tonynajjar** [ros2/rosbag2#1095]
## Description

** Clear and concise description of the feature that you'd like to exist, from a user's perspective. Don't get into implementation details, describe what you want it to do. Put any consideration of alternate features that might solve your problem as well. **

We can already include/exclude topics by name/regex, it would be nice to include/exclude topics by type. For my particular case, I'd like to avoid recording any Pointcloud2 to avoid an accidental size increase. Another example scenario would be to exclude all topic types that can't be visualized in Rviz 

## Related Issues

https://github.com/ros2/rosbag2/issues/560

## Completion Criteria

** What needs to be true before we can call this "Done"? Bullet lists are appropriate. **

## Implementation Notes / Suggestions

** If you have ideas about how this feature might be accomplished, put them here. Note that this is just a suggestion to the implementer, so feel free to speculate. **

## Testing Notes / Suggestions

** All features in this project need tests. Please give some input on cases that will need to be tested - and how the testing might be implemented. **

**Comment by tonynajjar** [comment]
This is solved with https://github.com/ros2/rosbag2/pull/1582?

**Comment by ahcorde** [comment]
I think so. PRs are merged on rolling

**Comment by MichaelOrlov** [comment]
- Closing as resolved in the #1582
