### ISSUE TITLE
request of new release of rosbag2 package

### ISSUE THREAD

**Issue by berndpfrommer** [ros2/rosbag2#1100]
There is an important commit in the "galactic" branch that has not made it into the Ubuntu packages for almost a year now.
I brought this up on the ROS discourse:

https://discourse.ros.org/t/preparing-for-galactic-sync-2022-08-05/26737/3

and was advised to open an issue.

Could you please release a new version of rosbag2 to be sync'ed? It would really simplify my setup. 
Thanks!

**Comment by tonynajjar** [comment]
The coincidence is crazy, I was just checking if there was any update regarding my [request](https://github.com/ros2/rosbag2/issues/823#issuecomment-1250926414) to sync and I find your fresh issue :)
