### ISSUE TITLE
Store metadata in db3 files directly

### ISSUE THREAD

**Issue by MichaelOrlov** [ros2/rosbag2#1109]
## Description
We have a proposal to make rosbag2 .db3 files self-contained. To achieve this goal we need to store metadata in .db3 files directly.

## Related Issues
Relates: 
- https://github.com/ros2/rosbag2/issues/1074
- https://github.com/ros2/rosbag2/issues/1108
- https://github.com/ros2/rosbag2/issues/782

## Completion Criteria
All `metadata` fields stored in .db3 files directly.

## Implementation Notes / Suggestions
On "Rosbag2 and Tooling WG meeting" from 2022-09-23 we discussed possible implementation and came to the following design decisions and proposals:
1. We decided to store metadata as a string in yaml format in newly created `schema`  table from https://github.com/ros2/rosbag2/issues/1108. 
It will be relatively easily to do since we already have all necessary methods for creating and parsing metadata from string read out from yaml file.
2. We will keep writing `metadata.yaml` file as before and rely on metadata from it. 
3. We will fallback on metadata from .db3 file directly if `metadata.yaml` absent or our parser failed to read or parse data from yaml file. 
The rational for this is that it's very convenient to operate with metadata stored in yaml file. i.e. It's very convenient to open yaml file in simple text editor to see what inside or edit it if necessary.

## Testing Notes / Suggestions
- Will need to add unit tests to cover read out and parsing metadata from .db3 files directly
- Will need to add unit tests to make sure that old versions of bag files supported. Need to make sure that we support backward compatibility.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-10-13/28213/1

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-11-17/28457/1

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2022-12-15/28840/1
