### ISSUE TITLE
Remove `rosbag2_tests` direct dependence on `sqlite3`

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#1112]
## Description

This is a code-decoupling issue. Currently `rosbag2_tests` (many of which tests are disabled on CI because they are very flaky), directly depends on the `sqlite3` storage implementation, which creates a hard coupling to this choice of storage plugin. The tests should be changed to use the generic storage APIs so that they can test any storage implementation.

**Comment by MichaelOrlov** [comment]
It would be ideally if they will be able to test two storage implementations (sqlite3 and mcap) on CI.
