### ISSUE TITLE
Reading and deserializing cdr messages

### ISSUE THREAD

**Issue by imouta** [ros2/rosbag2#1127]
Hello,

I'm been trying to parse a rosbag containg geometry_msgs/Vector3Stamped messages with C++. I managed to read the topics and their messages but the deserialized data from cdr_deserializer->deserialize seems wrong. The results are something like 2.68208e-310 instead of reasonable latitude/longitude/altitude values (the data represents gps values).

What could be the problem?

**Comment by MichaelOrlov** [comment]
Hi @imouta. 
Please refer to the 
https://github.com/ros2/rosbag2/blob/5b8b658b1f70a9f6184e4f6f31a42d50267f0b47/rosbag2_transport/test/rosbag2_transport/record_integration_fixture.hpp#L71-L86
and 
https://github.com/ros2/rosbag2/blob/5b8b658b1f70a9f6184e4f6f31a42d50267f0b47/rosbag2_test_common/include/rosbag2_test_common/memory_management.hpp#L47-L66
for reference implementation of how to de-serialize rosbag2 messages.

**Comment by MichaelOrlov** [comment]
Or here is another example how to read and de-serialize messages from recorded bag file.
https://github.com/ros2/rosbag2/blob/5b8b658b1f70a9f6184e4f6f31a42d50267f0b47/rosbag2_tests/test/rosbag2_tests/test_rosbag2_cpp_api.cpp#L94-L107

**Comment by imouta** [comment]
Thanks @MichaelOrlov for the reply. I actually was defining new type supports for geometry_msgs/Vector3Stamped messages instead of using them directly.
