### ISSUE TITLE
Recording a rosbag 

### ISSUE THREAD

**Issue by imouta** [ros2/rosbag2#1138]
## Description

I want to read messages from a bag and record them into a new rosbag. I found this tutorial about recording data from your own node:
[https://docs.ros.org/en/foxy/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-CPP.html](url)

However, I always get this error while running: 
`terminate called after throwing an instance of std::out_of_range`
`  What():  _Map_base::at`

## Related Issues

N/A

## Implementation Notes / Suggestions

N/A

## Testing Notes / Suggestions

N/A

Any help would be appreciated!

**Comment by MichaelOrlov** [comment]
- Closing as it doesn't relates to the rosbag2 issue.
 @imouta Please ask questions in https://answers.ros.org/
Rule of thumb to use issue tracker for real issues in rosbag2.

Please feel free to reopen this issue if you think it's really a problem in `rosbag2`.
