### ISSUE TITLE
Autodetect MCAP in rosbag2_cpp open

### ISSUE THREAD

**Issue by doisyg** [ros2/rosbag2#1158]
## Description

Ongoing discussion with @clalancette here: https://github.com/ros2/cartographer_ros/pull/67
Should rosbag automatically detects the bag format in the open method here ?
https://github.com/ros2/rosbag2/blob/c611a8010a0aaaba8bff47c42846aae2374fe81f/rosbag2_cpp/include/rosbag2_cpp/reader.hpp#L64-L78

And if yes, how ? Doing it based the file extension ?

Related:
- Same for python api ?
- Same for ros2 bag play cli ? (instead of passing the -s flag)

**Comment by MichaelOrlov** [comment]
@doisyg @clalancette MCAP or SQLite3 bags  auto detection has already been done in https://github.com/ros2/rosbag2/pull/1072
It's already works for `ros2 bag play`

As regards to the aforementioned `void open(const std::string & uri);` CPP and Python API - will need to make one line fix
in 
https://github.com/ros2/rosbag2/blob/c611a8010a0aaaba8bff47c42846aae2374fe81f/rosbag2_cpp/src/rosbag2_cpp/reader.cpp#L42
remove entire line with `storage_options.storage_id = "sqlite3";` initialization.
If `storage_options.storage_id` is an empty string - `SequentialReader` will try to auto-detect storage plugin by file extension.

**Comment by emersonknapp** [comment]
I just ran into this myself and have a solution in https://github.com/ros2/rosbag2/pull/1167
