### ISSUE TITLE
How can I use rosbag2_py in ROS Foxy?

### ISSUE THREAD

**Issue by imouta** [ros2/rosbag2#1178]
## Description
I want to record some topics with python. Usually, the package rosbag2_py is used for that but it is only available on foxy-future branch. How can I use it in Ros Foxy? 
I tried cloning the repository rosbag2 and rebuilding it but I got errors related to the foxy version of the repository that I previously installed. 

## System (please complete the following information)
 - OS: Ubuntu 20.04
 - ROS 2 Distro: Foxy

**Comment by emersonknapp** [comment]
`rosbag2_py` does not exist in the Foxy binary releases. The only way to use it is to check out the `foxy-future` branch of `rosbag2` and build that as part of your workspace.

I'll close this as "not enough info" for now. If `foxy-future` branch has broken (is not building successfully on top of the latest Foxy installs), then lets open a targeted bug report for that problem with error text included.

For general questions - I would recommend https://discourse.ros.org or https://robotics.stackexchange.com/?tags=ros (formerly https://answers.ros.org). GitHub issues should be used to track feature and bug development.
