### ISSUE TITLE
Unable to `ros2 bag record` in ROS2 Humble

### ISSUE THREAD

**Issue by tsadarsh** [ros2/rosbag2#1181]
## System (please complete the following information)
 - OS: Pop!_OS 22.04 LTS
 - ROS 2 Distro: Humble

## Description
I followed [guide](https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Recording-And-Playing-Back-Data/Recording-And-Playing-Back-Data.html) to install ros2 bag:
```
sudo apt-get install ros-humble-ros2bag \
                     ros-humble-rosbag2-storage-default-plugins
```
I am running a launch file of `realsense2_camera` which publishes the following topics:
```
/camera/accel/imu_info
/camera/accel/metadata
/camera/accel/sample
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressedDepth
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/color/points
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/metadata
/camera/extrinsics/depth_to_accel
/camera/extrinsics/depth_to_color
/camera/extrinsics/depth_to_depth
/camera/extrinsics/depth_to_gyro
/camera/gyro/imu_info
/camera/gyro/metadata
/camera/gyro/sample
/camera/imu
/parameter_events
/rosout
/tf_static
```
I want to record the `/camera/imu` and `/camera/depth/color/points` topic. So I created a new directory, `cd`'ed into it and ran `ros2 bag record -o trial /camera/depth/color/points /camera/imu` after sourcing. This is output that I get:
```
Traceback (most recent call last):
  File "/opt/ros/humble/bin/ros2", line 33, in <module>
    sys.exit(load_entry_point('ros2cli==0.18.3', 'console_scripts', 'ros2')())
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2cli/cli.py", line 89, in main
    rc = extension.main(parser=parser, args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2bag/command/bag.py", line 38, in main
    return extension.main(args=args)
  File "/opt/ros/humble/lib/python3.10/site-packages/ros2bag/verb/record.py", line 240, in main
    record_options.include_unpublished_topics = args.include_unpublished_topics
AttributeError: 'rosbag2_py._transport.RecordOptions' object has no attribute 'include_unpublished_topics'
```

**Comment by MichaelOrlov** [comment]
Hi @tsadarsh It looks like this is not a bug.
It looks like you have some leftovers in generated python bindings in particular in file `_transport.py` in your system.
Please double check if you have some overlays or leftovers in your python environment.

Parameter `include_unpublished_topics` definitely  present in "_transport.cpp"
https://github.com/ros2/rosbag2/blob/57181ac49a58e7c3cf503295e37b733804ec02e4/rosbag2_py/src/rosbag2_py/_transport.cpp#L273
 and we did not touched it since we added it to Humble in May 2022 in PR https://github.com/ros2/rosbag2/pull/1008

**Comment by tsadarsh** [comment]
@MichaelOrlov Thank you for the response. 
How do I check for overlays or leftovers in my python environment?

**Comment by emersonknapp** [comment]
How (exactly) did you set up the environment you used for recording? Such as:

```
sudo apt-get install ros-humble-rosbag2
source /opt/ros/humble/setup.bash
ros2 bag record ...
```

Are you also sourcing a workspace `insall/setup.bash`? If so, in what order? And, is any `rosbag2` source present in that workspace?

**Comment by MichaelOrlov** [comment]
- Closing as stale issue. Problem on user environment.
