### ISSUE TITLE
how to set storage_interfaces::IOFlag::READ_WRITE in python?

### ISSUE THREAD

**Issue by jonbakerfish** [ros2/rosbag2#1233]
Hi, is there any document or exmaple for rosbag2_py about modifying existing bag by appending new data to existing topics or creating new topics?

**Comment by emersonknapp** [comment]
There isn't actually any support in  rosbag2, currently, for appending data to an existing bag in any language interface. There is an `IOFlag::APPEND` definition that was intended to someday handle this case, but it is not implemented by any interfaces/storage implementations.

**Comment by MichaelOrlov** [comment]
- Closing as there are no solution for the question.
