### ISSUE TITLE
Record topics with qos-profile

### ISSUE THREAD

**Issue by DaphnaNanovel** [ros2/rosbag2#1236]
## Description
We are trying to record using ros2 bag record some topics. We use the eloquent version. The topics are published with the qos sensor_data profile. When recording using `ros2 bag record -o subset /topic_1 /topic_2` no messages are recorded. when recording using `ros2 bag record -a -o my_bag --qos-profile-overrides-path durability_override.yaml` we get the following error: 
`usage: ros2 [-h] Call `ros2 <command> -h` for more detailed usage. ...
ros2: error: unrecognized arguments: --qos-profile-overrides-path my_bag`

## System (please complete the following information)
 - OS: ubuntu 18
 - ROS 2 Distro: eloquent
 - Hardware: Jetson NX

**Comment by MichaelOrlov** [comment]
@DaphnaNanovel You are getting this error message because `--qos-profile-overrides-path` parameter not available on `eloquent` ros2 distro.
Earliest when It appears is in foxy-future https://github.com/ros2/rosbag2/tree/foxy-future
