### ISSUE TITLE
Cache Storage Record

### ISSUE THREAD

**Issue by alvaropascuaI** [ros2/rosbag2#1251]
I create a module to be able to record ros2 themes with python, I use this code, I have the problem that it doesn't record enough time, and the pc gets saturated, I have 4 GB of Ram and it stops recording.

I've been looking at rosbag2_py._storage.BagMetadata() functions - also that I can use with rosbag2_py._storage - I add to the constructor of rosbag2_py._storage.StorageOptions parameter max_cache_size = 0, but nothing the recording lasts the same time so I don't know what else I can do.

```
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
import rosbag2_py
import time
from rclpy.serialization import serialize_message

class StatusRecords(Node):
    def __init__(self):
        super().__init__('status_records')
        self.writer = rosbag2_py.SequentialWriter()
        
        year = time.localtime().tm_year
        month = time.localtime().tm_mon
        day = time.localtime().tm_mday
        hour = time.localtime().tm_hour
        minute = time.localtime().tm_min
        sec = time.localtime().tm_sec

        self.storage_options = rosbag2_py._storage.StorageOptions(uri=f'/media/discoduro3/rosbag2_{year}_{month}_{day}-{hour}_{minute}_{sec}',storage_id='sqlite3',max_bagfile_duration = 120)
        self.converter_options = rosbag2_py._storage.ConverterOptions()
        self.writer.open(self.storage_options, self.converter_options)

        self.subscription_camera1 = self.create_subscription(Image,'camera1/color/image_raw',self.topic_callback_camera1_color,10)
        self.topic_camera_visible1 = rosbag2_py._storage.TopicMetadata(name='camera1/color/image_raw',type='sensor_msgs/msg/Image',serialization_format='cdr')
        self.writer.create_topic(self.topic_camera_visible1)

        self.subscription_camera2 = self.create_subscription(Image,'camera2/color/image_raw',self.topic_callback_camera2_color,10)
        self.topic_camera_visible2 = rosbag2_py._storage.TopicMetadata(name='camera2/color/image_raw',type='sensor_msgs/msg/Image',serialization_format='cdr')         
        self.writer.create_topic(self.topic_camera_visible2)

    def topic_callback_camera1_color(self, msg):
        self.msg_camera1_visible = msg
        self.camera1_stamp = msg.header.stamp.sec        

        self.writer.write(
                'camera1/color/image_raw',
                serialize_message(self.msg_camera1_visible),
                self.get_clock().now().nanoseconds)

    def topic_callback_camera2_color(self, msg):
        self.msg_camera2_visible = msg
        self.camera2_stamp = msg.header.stamp.sec

        self.writer.write(
            'camera2/color/image_raw',
            serialize_message(self.msg_camera2_visible),
            self.get_clock().now().nanoseconds)

def main(args=None):
    rclpy.init(args=args)
    sbr = StatusRecords()
    rclpy.spin(sbr)
    rclpy.shutdown()


if __name__ == '__main__':
    main()

```

## System
 - OS: Ubuntu 20.04 
 - ROS 2 Distro: Ros2 Foxy 
 - Version: branch foxy - commit hash 197b09481a167d7fe9414c23945a778288f44a62

**Comment by MichaelOrlov** [comment]
@alvaropascuaI There are could be a lot of variables in "loop" affecting your experience and Foxy distro is pretty old to say something meaningful about it.  
Is there any particular reasons to not use `ros2 bag record <topic1> <topic2> ` command in favor of the customized python implementation for the recording?

Have you tried to record with `max_bagfile_duration = 0` ?

**Comment by alvaropascuaI** [comment]
I change version of my ros to rolling and works fine, i need to do some test more but i think works fine
I want to use a script of python, because i like generate a module of ros to can recording and i dont wanna to use a ros2 bag record <topic1> 
Now, i have other problem i dont know if i can asked you in this issue, i try to do colcon build on branch rolling and i have the next error i look this issue  #1229  and i launch command `apt install ros-rolling-rosbag2-storage-default-plugins `of but i have the same error and i launch before colcon source /opt/ros/rolling/setup.bash
![image](https://user-images.githubusercontent.com/97975075/222702312-b3f2a88e-7030-49b4-8351-77ffbb72ab27.png)

**Comment by MichaelOrlov** [comment]
@alvaropascuaI According to the https://github.com/ros2/rosbag2/issues/1229#issuecomment-1379651401 `apt update && apt upgrade -y` should help with missing dependencies.

**Comment by emersonknapp** [comment]
As an extra note - I would recommend using a stable distribution such as Humble. Rolling is the bleeding edge code and can change at any time.

I'm going to close this issue as resolved for now. Foxy will be end-of-life in May so I do not expect us to do any major efforts there. Please reopen if you feel we need to address a specific issue in a newer distribution.
