### ISSUE TITLE
Add option to CLI to start recorder with warning not info log-level

### ISSUE THREAD

**Issue by bijoua29** [ros2/rosbag2#1255]
## Description

When running 'ros2 bag record', I don't want all the normal console output that indicates what topic are being subscribed to. I would like to start the recorder node with 'warning' or 'error' log level instead of info.

## Related Issues

N/A

## Completion Criteria

Add option to 'ros2 bag record' for log level

## Implementation Notes / Suggestions

N/A

## Testing Notes / Suggestions

N/A

**Comment by bijoua29** [comment]
A --log-level argument with options debug, info, warn, error, fatal would be the preferred solution

**Comment by emersonknapp** [comment]
Closing this one as duplicate of #288
