### ISSUE TITLE
`Warning: class_loader.ClassLoader: SEVERE WARNING when using ros2 bag play for compressed bag

### ISSUE THREAD

**Issue by mhaukeland** [ros2/rosbag2#1278]
## Description
I want to use ros2 bag play on a compressed ros2 bag I have recorded. It seems to work fine, but I get a SEVERE WARNING message at the end of the bag play.

### Expected Behavior
The expected behaviour is that this warning message should not be displayed.

### Actual Behavior
When I use ros2 bag play a_compressed_bag. I get the following warning message:
`Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
[ros2-2]          at line 127 in ./src/class_loader.cpp`
My bag is compressed using message-compression mode and zstd-compression.

## To Reproduce
** Steps to reproduce the behavior, e.g.
Play a compressed bag using ros2 bag play a_compressed_bag and observe the displayed warning message at the end of the playback.

## System (please complete the following information)
 - OS: Ubuntu 22.04
 - ROS 2 Distro: humble
 - Version: release-latest

**Comment by MichaelOrlov** [comment]
@mhaukeland Is it compression per message or per file?

**Comment by MichaelOrlov** [comment]
@mhaukeland Never mind. I've figured it out.
Will be fixed when #1299 will be backported to humble. Therefore not early than merge freeze to rolling will end.

**Comment by MichaelOrlov** [comment]
- Closing as will not be fixed on humble, since the fix in #1299 changes the order of the private variables and breaking ABI compatibility.

**Comment by MichaelOrlov** [comment]
- Closing as done since an alternative backport to the Humble has been made in the #1362
