### ISSUE TITLE
Test failure `rosbag2_cpp/test_time_controller_clock` on nightly_win_rep 

### ISSUE THREAD

**Issue by Yadunund** [ros2/rosbag2#1282]
CI: https://ci.ros2.org/view/nightly/job/nightly_win_rep/2955/testReport/(root)/projectroot/test_time_controller_clock/

```
C:\ci\ws\src\ros2\rosbag2\rosbag2_cpp\test\rosbag2_cpp\test_time_controller_clock.cpp(168): error: Value of: end - start >= std::chrono::seconds(1)
  Actual: false
Expected: true
C:\ci\ws\src\ros2\rosbag2\rosbag2_cpp\test\rosbag2_cpp\test_time_controller_clock.cpp(169): error: Value of: sleep_result
  Actual: false
Expected: true
[  FAILED  ] TimeControllerClockTest.unpaused_sleep_returns_true (999 ms)
```

**Comment by MichaelOrlov** [comment]
This is flaky test - addressing in https://github.com/ros2/rosbag2/pull/1290

**Comment by emersonknapp** [comment]
I think I just ran into this again in a [CI build](https://ci.ros2.org/job/ci_windows/19625/) - I'm not sure it's actually fixed.

Running a Windows build on just `test_time_controller_clock` with `--retest-until-failed 100`

[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=19628)](https://ci.ros2.org/job/ci_windows/19628/)

**Comment by emersonknapp** [comment]
https://github.com/ros2/rosbag2/pull/1367 also is investigating this - I am reopening the issue while investigation is ongoing

**Comment by MichaelOrlov** [comment]
@emersonknapp It seems it failed with a different error message on your CI job.
Please refer to my post here https://github.com/ros2/rosbag2/pull/1371#issuecomment-1581652658 for details.
