### ISSUE TITLE
Test failure `rosbag2_transport/test_play_services__rmw_connextdds` on nightly_win_rep

### ISSUE THREAD

**Issue by Yadunund** [ros2/rosbag2#1283]
CI: https://ci.ros2.org/view/nightly/job/nightly_win_rep/2955/testReport/(root)/projectroot/test_play_services__rmw_connextdds/

**Comment by MichaelOrlov** [comment]
This is an old known issue described here
https://github.com/ros2/rosbag2/issues/862
It seems we recently had some fixes on the FastRTPS side as part of the
https://github.com/ros2/rclcpp/issues/2039 (BTW it seems with some side
effects) but not on other RMWs.

**Comment by MichaelOrlov** [comment]
- Closing as duplicate of the #862
