### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by laurafbec** [ros2/rosbag2#1285]
## Description

Hi everyone. I would like to know is there is a way to enable encryption functionalities when creating a rosbag file from a ROS2 python node in sqlite3 or mcap format. Thanks in advance.

**Comment by emersonknapp** [comment]
No - there is no encryption functionality in rosbag2. I think it would be a large project requiring very careful design - so I'm going to close this issue in favor of tracking anything like that in a much more specific design discussion ticket. GitHub's not really the place for general questions - I might suggest https://answers.ros.org for questions, or https://discourse.ros.org for discussions
