### ISSUE TITLE
Rolling to Humble Update request [(#1291)] 

### ISSUE THREAD

**Issue by AswinkarthikeyenAK** [ros2/rosbag2#1308]
Hi @emersonknapp

Recently, noticed a updated to the rolling branch (https://github.com/ros2/rosbag2/pull/1291)) [0.22.0](https://github.com/ros2/rosbag2/releases/tag/0.22.0), link [here](https://github.com/ros2/rosbag2/commit/a632922b693abde41147966796b11224861880aa), 

Is there a chance this will be applied to the humble branch as well?

Thanks

**Comment by emersonknapp** [comment]
#1291 significantly changes/breaks the API, which is not allowed within a stable distribution (Humble). It cannot be backported to Humble
