### ISSUE TITLE
ros2bag: Documentation should reflect that `--ignore-leaf-topics` is not compatible with `--include-unpublished-topics`

### ISSUE THREAD

**Issue by timonegk** [ros2/rosbag2#1313]
**Required Info:**
- Version or commit hash: 0.24.1

The documentation/`--help` page should reflect that `ros2 bag record` with `--include-unpublished-topics` does not work when `--ignore-leaf-topics` is also specified.

**Comment by christophebedard** [comment]
This should probably go here instead: https://github.com/ros2/rosbag2

**Comment by clalancette** [comment]
Yes, good catch.  I'll move it over there.

**Comment by emersonknapp** [comment]
Closing as fixed in https://github.com/ros2/rosbag2/pull/1344 (rolling) and https://github.com/ros2/rosbag2/pull/1345 (iron backport)
