### ISSUE TITLE
Bag record help message errors and inconsistencies

### ISSUE THREAD

**Issue by hwoithe** [ros2/rosbag2#1327]
## Description
There are few errors and inconsistencies in the messages produced by `ros2 bag record --help`.

- Missing period at the end of the sentence. The backslash also seems out of place compared to how the other help messages are constructed.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L57

- Missing period at the end of the sentence.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L61

- Missing period at the end of the sentence.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L107

- Missing space at the end of the string.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L121

- Missing space at the end of the string.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L123

- Missing space at the end of the string. Change magitude to magnitude.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L124

- Missing space at the end of the string.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L125

- Missing space at the end of the string.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L138

- Missing period at the end of the sentence.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L162

- Missing period at the end of the sentence.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/verb/record.py#L167

- Is the "R|" a mistake?
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/api/__init__.py#L199

- Change overriden to overridden.
https://github.com/ros2/rosbag2/blob/65c889e1fa55dd85a148b27b8c27dadc73238e67/ros2bag/ros2bag/api/__init__.py#L200

### Expected Behavior
Consistent formatting and no errors in the help message.

### Actual Behavior
There are a few errors and inconsistencies in the help message.

## To Reproduce
Execute `ros2 bag record --help`.

## System
 - OS:  Ubuntu Jammy
 - ROS 2 Distro: Iron
 - Version: prerelease

**Comment by clalancette** [comment]
See #1329 for fixes.

**Comment by hwoithe** [comment]
Thank you for the quick turnaround.
