### ISSUE TITLE
Build fails if you don't have fastrtps

### ISSUE THREAD

**Issue by ivanpauno** [ros2/rosbag2#136]
The building of `rosbag2_converter_default_plugins` is failing not quietly when you don't have `rmw_fastrtps_cpp`. I think that's not ok, you should be able to build ros2 without it (e.g.: only with opensplice or connext).

Failing CI builds with only opensplice (from [comment](https://github.com/ros2/rmw_opensplice/issues/264#issuecomment-505181300)):

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7421)](http://ci.ros2.org/job/ci_linux/7421/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3572)](http://ci.ros2.org/job/ci_linux-aarch64/3572/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6089)](http://ci.ros2.org/job/ci_osx/6089/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7244)](http://ci.ros2.org/job/ci_windows/7244/)

Further info:

The problem is here:
https://github.com/ros2/rosbag2/blob/2ad74a4d7a81bcb82e084d5d26c60415c644766e/rosbag2_converter_default_plugins/CMakeLists.txt#L53-L57

The build is only failing when `BUILD_TESTING=1`, but that's usual.

**Comment by dirk-thomas** [comment]
@Karsten1987 can you please address this since it make building without FastRTPS more effort.
