### ISSUE TITLE
Backport close functionality to writer in humble

### ISSUE THREAD

**Issue by bernatgaston** [ros2/rosbag2#1364]
## Description

rosbagcpp writer in rolling has the close functionality which is necessary to create a service that starts or stops rosbag2. Otherwise, a sqlite error is launched the second time you call a rosbag with the same topics. However, the humble version does not have it.

## Related Issues
https://github.com/ros2/rosbag2/issues/876

## Completion Criteria

Close functionality added to writer

## Implementation Notes / Suggestions
I created a PR already with the code since it is quite straightforward
https://github.com/ros2/rosbag2/pull/1363

## Testing Notes / Suggestions
I don't know if a test should be added.

**Comment by MichaelOrlov** [comment]
- Closing as resolved in the #1363
