### ISSUE TITLE
GCC 13 missing cstdint include

### ISSUE THREAD

**Issue by yameatmeyourdead** [ros2/rosbag2#1379]
Building with GCC13 fails due to a missing `#include <cstdint>` at https://github.com/ros2/rosbag2/blob/e552f15d35cc3318c21efeee4f03675d94545725/rosbag2_storage/include/rosbag2_storage/storage_options.hpp#L20

Without it, storage_options fails to compile at https://github.com/ros2/rosbag2/blob/e552f15d35cc3318c21efeee4f03675d94545725/rosbag2_storage/include/rosbag2_storage/storage_options.hpp#L35 and base_io_interface fails to compile at https://github.com/ros2/rosbag2/blob/e552f15d35cc3318c21efeee4f03675d94545725/rosbag2_storage/include/rosbag2_storage/storage_interfaces/base_io_interface.hpp#L28

**Comment by emersonknapp** [comment]
PRs welcome!
