### ISSUE TITLE
Error playing a recorderd .mcap ros2 bag : Could not open 'rosbag2_xxx.mcap' with 'sqlite3'.

### ISSUE THREAD

**Issue by ronyshaji** [ros2/rosbag2#1406]
## Description
ROS bag with .mcap format doesnot in ROS FOXY version as it gives the following error:

```
[ERROR] [1688370810.619549312] [rosbag2_storage]: Could not open 'rosbag2_xxx_all_topics/rosbag2_2023_05_02-06_37_29_0.mcap' with 'sqlite3'. Error: Failed to setup storage. Error: Error when processing SQL statement. SQLite error (26): file is not a database
[ERROR] [1688370810.619595049] [rosbag2_storage]: Could not load/open plugin with storage id 'sqlite3'.
[ERROR] [1688370810.619624357] [rosbag2_transport]: Failed to play: No storage could be initialized. Abort
```

### Expected Behavior

The recorded ROS bag should play when i execute the command **'ros2 bag play  rosbag2_xxx_all_topics'**
The ' rosbag2_jupiter_all_topics/' folder has the .yaml file as well as .mcap ros bag. I checked and sqlite3 is already installed and updated.

### Actual Behavior

Instead of playing the recorded ROS bag, it is showing an error.

## To Reproduce
1. Open ubuntu 20.04 in wsl.
2. Source the ROS2 Foxy verison
3. Run the command **'ros2 bag play  rosbag2_xxx_all_topics'**

## System (please complete the following information)
 - OS: Windows 10 wsl2 - Ubunutu 20.04
 - ROS 2 Distro: ROS2 Foxy

**Comment by ronyshaji** [comment]
@MichaelOrlov Do you have any idea about this? I found you have some issue like this earlier?

**Comment by emersonknapp** [comment]
Could you please provide the information requested from the bug report template? https://github.com/ros2/rosbag2/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

I've copy-pasted the template form into the description, if you would kindly fill out the remaining fields it will help to understand the issue

**Comment by MichaelOrlov** [comment]
@ronyshaji I agree with @emersonknapp we need more info.
At first glance it looks like you are trying to playback some mcap file on some old ROS 2 distro which doesn't have proper support for it.

**Comment by ronyshaji** [comment]
@emersonknapp and @MichaelOrlov The issue has been updated as per the template.

**Comment by MichaelOrlov** [comment]
@ronyshaji Yep. My preliminary guess was correct.  
`ROS 2 Foxy` doesn't support MCAP file format and it is already reached its end of life.
