### ISSUE TITLE
Setting compression mode when using rosbag2_py.SequentialCompressionWriter

### ISSUE THREAD

**Issue by bmdyrdal** [ros2/rosbag2#1407]
Hi folks,

I'm writing a component for recording specific topics, and wanted to use the rosbag2_py library. 
I'm having some difficulties finding out how I can set the compression mode? I see that you can set it in the bagmetadata, but I don't see how I can use that?
Anyone who has any examples of how I can do this? 

Thanks in advance!

**Comment by MichaelOrlov** [comment]
@bmdyrdal What storage backend and ROS 2 distro are you going to use?

**Comment by MichaelOrlov** [comment]
If this is for Iron or Rolling - we have a special field in the `StorageOptions`
https://github.com/ros2/rosbag2/blob/b6f5b43feb43a6481f4f203ee14ad10f02c7a55d/rosbag2_storage/include/rosbag2_storage/storage_options.hpp#L53
Please refer to the https://github.com/ros2/rosbag2#recording-with-a-storage-configuration and https://github.com/ros2/rosbag2/blob/rolling/rosbag2_storage_mcap/README.md#writer-configuration and https://github.com/ros2/rosbag2/blob/rolling/rosbag2_storage_sqlite3/README.md#storage-configuration-file 
to see how to write config files for storage backend.

**Comment by simonsag96** [comment]
As far as I see the constructor of the Sequential Compression Writer has an argument of type `rosbag2_compression::CompressionOptions` 

https://github.com/ros2/rosbag2/blob/d788e518b3a93acb61226d993e3d3095913f16b1/rosbag2_compression/include/rosbag2_compression/sequential_compression_writer.hpp#L61-L63

However, this argument is not bound to Python accordingly in `rosbag2_py`
https://github.com/ros2/rosbag2/blob/d788e518b3a93acb61226d993e3d3095913f16b1/rosbag2_py/src/rosbag2_py/_writer.cpp#L109-L110

Furthermore, the `rosbag2_compression::CompressionOptions` is not bound to Python.

So wouldn't it be correct to adapt the pybind11 code in rosbag2_py to adapt the API of the cpp version?

**Comment by bmdyrdal** [comment]
@MichaelOrlov Using Humble, store it using sqlite3 in our file system. 
Works fine using it from the command line.

@simonsag96 Is spot on with his comment! :+1: 

While waiting for this I ended up writing a python node which starts the recording as a subprocess.

**Comment by MichaelOrlov** [comment]
@bmdyrdal @simonsag96 Yes. The solution would be to provide pybind11 code in rosbag2_py package to map `rosbag2_compression::CompressionOptions` to Python and use it as the default parameter in the Python version of the `SequentialCompressionWriter`. 

But unfortunately, I don't have time for this task.  If some of you can provide a PR it would be great, otherwise, this task will go in the backlog.

**Comment by simonsag96** [comment]
Thanks for your answer @MichaelOrlov!

I could implement this over the course of next week!

**Comment by asymingt** [comment]
@simonsag96  I needed this myself today, so I put together this PR: https://github.com/ros2/rosbag2/pull/1425
