### ISSUE TITLE
README link without text

### ISSUE THREAD

**Issue by udalmia94** [ros2/rosbag2#1445]
## Description
The rolling branch [README doc on line 15](https://github.com/ros2/rosbag2/blob/rolling/README.md?plain=1#L15) has a link without text so it doesn't render. On the landing page of this repo you see "To build from source, follow the instructions in" without anything following that.

**Comment by emersonknapp** [comment]
Created https://github.com/ros2/rosbag2/pull/1446 - In the future I encourage you to open a PR of your own! Contributions are very welcome, especially documentation updates.
