### ISSUE TITLE
python node with Recorder does not exit with CTRL-C

### ISSUE THREAD

**Issue by tonynajjar** [ros2/rosbag2#1458]
## Description
A rclpy node instantiating a `rosbag2_py.Recorder` does not exit with CTRL-C

### Expected Behavior
It should exit cleanly

### Actual Behavior
It just hangs

## To Reproduce
```
import rclpy

from rclpy.node import Node
from rosbag2_py import Recorder

class RosBagRecorder(Node):
    def __init__(self):
        super().__init__("rosbag_recorder")
        self.recorder = Recorder()

def main():
    rclpy.init()
    node = RosBagRecorder()
    rclpy.spin(node)


if __name__ == "__main__":
    main()
```

## System (please complete the following information)
 - OS: Ubuntu 22
 - ROS 2 Distro: Iron
 - Install Method: source
 - Version: iron latest

## Additional context
** Add any other context about the problem here **

**Comment by MichaelOrlov** [comment]
@tonynajjar The code behave as expected by design.  
It doesn't make sense to create rosbag2 recorder and spin node directly.  
We have SingleThreadedExecuter inside `Recorder::record(..)` method which will spin the node and gracefully handle `SIGINT` and `SIGTERM` signals. 

in your example, you are missing call for the 
```
recorder.record(storage_options, record_options, "node_name")
```

Please refer to the https://github.com/ros2/rosbag2/blob/dcd239ceea842752c344f0048572deb5f502feb8/ros2bag/ros2bag/verb/record.py#L255-L260
as an example of how to properly use it.

**Comment by tonynajjar** [comment]
The instantiation of a `Recorder` in any python script will block CTRL-C

```
from rosbag2_py import Recorder
import time

recorder = Recorder()
time.sleep(10)
```

Try to exit this script with CTRL-C before the sleep ends -> doesn't exit. Maybe CTRL-C will work if `recorder.record` is called but that shouldn't be a requirement

**Comment by MichaelOrlov** [comment]
@tonynajjar Yes it is true. We override signal handlers in the recorder constructor to handle them further on in blocking `recorder::record(..)` method.   
Perhaps we can change this behavior and install signal handlers at the beginning of the `recorder::record(..)` method.

Out of curiosity what would be a use case for instantiating `Recorder()` instance and not using `recorder::record(..)` method after that?

**Comment by tonynajjar** [comment]
Well the use case is that I want to make a Node which has a service server that when called will trigger the recording of a bag. For the recording I use this recorder, but it only starts recording when the service is called

**Comment by tonynajjar** [comment]
The use case is I want to have a node with a service server that when called, will start recording a bag with the help of the Recorder. A bit like what is asked in https://github.com/ros2/rosbag2/issues/685

So the Recorder exists but we only start recording when the service is called

**Comment by fujitatomoya** [comment]
> The use case is I want to have a node with a service server that when called, will start recording a bag with the help of the Recorder.

@tonynajjar https://github.com/ros2/rosbag2?tab=readme-ov-file#controlling-recordings-via-services does not work for your use case?
