### ISSUE TITLE
How to read or extract a subset of messages in a ros2 bag file based on start and end time stamp ?

### ISSUE THREAD

**Issue by prats778** [ros2/rosbag2#1489]
## **Description**

I want to extract or read a subset of a ros2 bag file(db3/mcap) filtered on the basis of topics and containing messages information similar to that of rosbag.Bag,read_messages(topics, start_time, end_time) function in ROS1.

To my understanding ,the SequentialReader class has seek function to reach a specific timestamp in the bag file but is there any way to directly extract a part of bagfile based on timestamps?

## **SYSTEM STATUS**

Linux : ubuntu 22.04 [Humble]

**Comment by MichaelOrlov** [comment]
Hi @prats778 We recently added such functionality to the `ros2 bag convert` verb
- See https://github.com/ros2/rosbag2/pull/1455 for details
