### ISSUE TITLE
Duplicate self.subscription call

### ISSUE THREAD

**Issue by Hommus** [ros2/rosbag2#1494]
Just double checking, is there meant to be 2 `self.subscription` included in this example?

https://github.com/ros2/rosbag2/blob/d6030c4c26443c87a094c3091c3cd2059da3816d/rosbag2_examples/rosbag2_examples_py/rosbag2_examples_py/simple_bag_recorder.py#L39-L44

**Comment by clalancette** [comment]
> Just double checking, is there meant to be 2 `self.subscription` included in this example?

Yes; see http://docs.ros.org/en/rolling/Tutorials/Advanced/Recording-A-Bag-From-Your-Own-Node-Py.html#examine-the-code .

In the future, please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
