### ISSUE TITLE
Split recordings into chunks by size while recording

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#150]
## Description
rosbag1 had the ability to split bags while recording, either by size or by time

Feature request: add the ability to split rosbags by size boundaries (time will be tracked in a separate issue)

## Acceptance criteria
* extension to recorder functionality to split recordings along size boundaries
* commandline arguments to ros2bag to expose this new functionality

**Comment by Karsten1987** [comment]
@emersonknapp with the latest set of PRs landed and released, can this ticket be closed?

**Comment by emersonknapp** [comment]
I believe there is one last PR we're trying to put in, that adds some extra input sanitization for the CLI entrypoint to this feature, before we call it done. @prajakta-gokhale is that correct?

**Comment by prajakta-gokhale** [comment]
> I believe there is one last PR we're trying to put in, that adds some extra input sanitization for the CLI entrypoint to this feature, before we call it done.

That is correct for the functionality to be complete. We are tracking it in https://github.com/ros-security/aws-roadmap/issues/6.


We have 2 more tasks related to splitting that we're planning to work on before closing this:
1. End-to-end testing (https://github.com/ros-security/aws-roadmap/issues/10 )
2. CLI enhancement to read in human-readable split bag sizes (https://github.com/ros-security/aws-roadmap/issues/64)

**Comment by wjwwood** [comment]
@emersonknapp or anyone on this issue can you update the description if part of the functionality is completed (@piraka9011 suggested the by size is done, but not the by time).

**Comment by emersonknapp** [comment]
@wjwwood thanks for the ping - I am going to reduce the scope of this issue to specify splitting by size, close this one, and open a new issue to request the feature of splitting by time
