### ISSUE TITLE
Resort: When playing bag in ROS2 Humble, the bandwidth is very low

### ISSUE THREAD

**Issue by DMUZhangXianglong** [ros2/rosbag2#1502]
Hardware Lenovo Saver y9000P2023 CPU i9-13900hx 16G memory solid-state drive (Western 770 black drive), software environment is ubuntu22.04. Problem: After playing the bag, 
use ROS2 topic bw/rslidar_ point check bandwidth (only a few hundred kb/s), as shown in the following figure.
But on another computer, the normal speed can reach 7-8M/s, may I ask why?
![截图 2023-11-23 18-09-24](https://github.com/ros2/rosbag2/assets/73846756/e1d04c79-e9cc-4a96-aa89-420ab69f7b1f)

**Comment by MichaelOrlov** [comment]
@zxl152723 Hmm, don't know why off the top of my head.  
If thinking logically, if you see the correct bandwidth receiving on another computer it does mean that rosbag2 player publishing with the correct rate, right? 
It means this is not a rosbag2 bug, correct?

Might be default QoS settings on the receiver side or the maximum allowed buffer in the kernel for the Ethernet adapter.

**Comment by DMUZhangXianglong** [comment]
Thank you for your help，I have another question. When I play the ros2 bag ，the hz of the topic “/rslidar_points” is so low, it should be 10Hz, but in my device it only 0.9hz，how can I set the Qos？

when I playing the bag in my device and using the “”ros2 topic hz /rslidar_points” to view  with another device ，the hz is about 10Hz，why？

**Comment by MichaelOrlov** [comment]
@DMUZhangXianglong I don't actually know what causing the slowdown of the publishing stream. 
We need a minimum valuable reproducer to be able to make any analysis.

Please refer to the https://docs.ros.org/en/rolling/How-To-Guides/Overriding-QoS-Policies-For-Recording-And-Playback.html#using-qos-overrides for QoS settings overriding.

**Comment by MichaelOrlov** [comment]
- Closing a stale issue without the possibility of reproducing it.
