### ISSUE TITLE
All bags being opened when playing back multiple bag files. 

### ISSUE THREAD

**Issue by lowellm91** [ros2/rosbag2#1512]
I requested a feature to play multiple bags in a single folder sequentially. It was mentioned that this feature is present in rosbag2 which means there is an error going on(I hope it's OK to create a second thread). As can been seen when I play the folder every bag is opened but only the first bag appears to output via echo. I checked using rqt if the time-stamps between each file were increasing and they are so I'm not sure what could be the hangup.

![Screenshot from 2023-12-13 21-36-26](https://github.com/ros2/rosbag2/assets/152669045/bdaa33a6-0054-4187-9c90-39986c866dfe)

[metadata.txt](https://github.com/ros2/rosbag2/files/13669193/metadata.txt)

**Comment by MichaelOrlov** [comment]
@lowellm91 We need a minimum valuable reproducer for this problem.

**Comment by lowellm91** [comment]
> @lowellm91 We need a minimum valuable reproducer for this problem.

Thank you, I will check and see if I can provide one. I know the bag file was recorded with Foxy and then split into a collection of smaller bags for easier transmission. I am using Humble - could this be the problem?

**Comment by MichaelOrlov** [comment]
>  I am using Humble - could this be the problem?

It shouldn't be a problem we are trying to keep backward compatibility in the new versions of the rosbag2.

**Comment by lowellm91** [comment]
Hi, I apologize as I was not able to provide the data, I will close the issue as it might be related to the bag files themselves.

**Comment by lowellm91** [comment]
Hi, I apologize as I was not able to provide the data, I will close the issue as it might be related to the bag files themselves.
