### ISSUE TITLE
Docker- No storage id specified, and no plugin found that could open URI

### ISSUE THREAD

**Issue by adijams01** [ros2/rosbag2#1573]
## Description
I am trying to play rosbag on docker
I ran the launch file for lidar it worked, but while playing the rosbag i am getting error

### Expected Behavior
it should have been open and viewed on rviz2

### Actual Behavior
```
root@fbae67ab16dd:~/ros2_ws# ros2 bag play /my_src/ros2_ws/src/dataset/walking_dataset.bag

closing.

closing.
[ERROR] [1708928873.483955608] [rosbag2_storage]: No storage id specified, and no plugin found that could open URI
No storage could be initialized from the inputs.
```

## To Reproduce
[link](https://github.com/TixiaoShan/LIO-SAM/blob/ros2/Dockerfile) to dockerfile
[link](https://drive.google.com/file/d/1fpoOPVxbQbFmmLd2Pe2u8LnYueZLGtOm/view?usp=drive_link) to walking dataset's rosbag
```
docker run --name Lidar_r2 -it -v $PWD/src:/my_src -v /tmp/.X11-unix:/tmp/.X11-unix:rw --env=DISPLAY 86d3c223e99b bash
docker container start -i Lidar_r2
```
once in container 
on first terminal use launch 
second terminal inside container  play rosbag 

## System (please complete the following information)
 - OS: Ubuntu 20.04
 - ROS 2 Distro: Foxy (humble in docker)

Thank you

**Comment by fujitatomoya** [comment]
@adijams01 bag file is more than 3.5GB so i did not download it. can you check the info for the bagfile?

```bash
root@tomoyafujita:~/ros2_ws/colcon_ws# ros2 bag info -v rosbag2_2024_02_26-13_10_17/

Files:             rosbag2_2024_02_26-13_10_17_0.mcap
Bag size:          24.0 KiB
Storage id:        mcap
ROS Distro:        rolling
Duration:          4.399s
Start:             Feb 26 2024 13:10:17.814 (1708981817.814)
End:               Feb 26 2024 13:10:22.213 (1708981822.213)
Messages:          25
Topic information: Topic: /chatter | Type: std_msgs/msg/String | Count: 5 | Serialization Format: cdr
                   Topic: /events/write_split | Type: rosbag2_interfaces/msg/WriteSplitEvent | Count: 0 | Serialization Format: cdr
                   Topic: /parameter_events | Type: rcl_interfaces/msg/ParameterEvent | Count: 0 | Serialization Format: cdr
                   Topic: /rosout | Type: rcl_interfaces/msg/Log | Count: 20 | Serialization Format: cdr
Service:           0
Service information: 
```

and the question is what ROS 2 distribution is used to record this bag file? it appears that rosbag2 in the humble container cannot open the bag file. probably it finds the inconsistency for the bag file.

**Comment by MichaelOrlov** [comment]
@adijams01 Can you please try to run 
```
ros2 bag list storage --verbose
```
in your Docker.
What output do you see?

**Comment by Spirquel** [comment]
it's because you use a file with ".bag" and these files is for ROS1 (the ros for students, university and search). So for ROS2 the rosbag2 file is ".db3". it exists others files like ".zstd" which is a compressor (like a .zip) for a files rosbag.
".mcap" and ".sqlite3" i don't very understand what it is but if it interest you, the README talk about that.
If you want to convert your .bag the answer is [here](https://github.com/ros2/rosbag2_bag_v2/blob/master/README.md) but you have to install [ROS1 Distribution](http://wiki.ros.org/Distributions) and [ROS2 Distribution](https://docs.ros.org/en/humble/Releases.html)

**Comment by adijams01** [comment]
Thank you, for your responses now i am able to view it in rviz

**Comment by Spirquel** [comment]
I have a good new. If you want to convert .bag to .db3, it exist a python code with like name "rosbags" the link is [here](https://pypi.org/project/rosbags/) and for that you needn't to install ros1 distribution. Use the command "rosbags-convert name_file.bag".
