### ISSUE TITLE
Move FilesystemHelper class to ros2/rcpputils repo and deprecate files within rosbag2

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros2/rosbag2#159]
Now that we have `ros2/rcpputils` repo, I am very much in favor of moving the `FilesystemHelper` class altogether to that repo and deprecate the files within `rosbag2`.

_Originally posted by @Karsten1987 in https://github.com/ros2/rosbag2/timeline_

**Comment by emersonknapp** [comment]
This is done
