### ISSUE TITLE
Recording bag splitting optimizations

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros2/rosbag2#160]
This comes from comments in #158 .

* https://github.com/ros2/rosbag2/pull/158#discussion_r323845525
Opening the next database should happen concurrent to still writing to the old database to make the switching as small as possible.

**Comment by emersonknapp** [comment]
This can potentially overflow the incoming queue if it takes too long

**Comment by piraka9011** [comment]
The proposed approach is to spin up a new thread to process the splitting.

**Comment by emersonknapp** [comment]
The latest architecture removes the need for this ticket. Closing as outdated - reopen if needed
