### ISSUE TITLE
How to use ros2 bag convert decompression a .db3

### ISSUE THREAD

**Issue by LHZ-code** [ros2/rosbag2#1626]
use ros2 bag record --compression-mode message --compression-format zstd get a .db3

now how to use ros2 bag conver to decompression the .db3

**Comment by MichaelOrlov** [comment]
@LHZ-code That should be pretty much straight forward and `ros2 bag convert` will handle it automatically.
For instance:
```
$ ros2 bag convert -i compressed_bag1 -o out.yaml

# out.yaml
output_bags:
- uri: uncompressed_bag1
  all: true
```

**Comment by MichaelOrlov** [comment]
Please ask questions related to the ROS and rosbag2 in the https://robotics.stackexchange.com/
