### ISSUE TITLE
[rosbag2_py] Typo in Recorder's signal restoration? (second `SIGTERM` should be `SIGINT`)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ros2/rosbag2#1686]
## Description
Per comment in
https://github.com/ros2/rosbag2/issues/1678#issuecomment-2143936223
Line 239 should be `SIGINT`, not `SIGTERM`:
https://github.com/ros2/rosbag2/blob/8c94497f4a13464538457d81433d85fa13c760a9/rosbag2_py/src/rosbag2_py/_transport.cpp#L234-L240

fyi @MichaelOrlov 

### Expected Behavior
Line 239 should be `SIGINT`, not `SIGTERM`

### Actual Behavior
It is `SIGTERM`

## To Reproduce
See code.

## System (please complete the following information)
 - OS: Any
 - ROS 2 Distro: Humble
 - Install Method: Any
 - Version: humble

## Additional context
Relates #1678

**Comment by MichaelOrlov** [comment]
- Closing as fixed in the #1687
