### ISSUE TITLE
ros2 bag play error

### ISSUE THREAD

**Issue by qxang1001** [ros2/rosbag2#1728]
I can't play my bag in my machine.Is anyone knows what would cause the problem?
I want to play my bag file normally(no problem in bag file).
When I run `ros2 bag play imu_data`
It stops and output:
[INFO] [1719402363.399387869] [rosbag2_storage]: Opened database 'imu_data/rosbag2_2024_06_15-18_50_19_0.db3' for READ_ONLY.
Segmentation fault (core dumped)
![微信图片_20240626201305](https://github.com/ros2/rosbag2/assets/105415412/bbaef5ef-ece1-4f25-9d36-ceb5da9a83db)
Env: ubuntu 20.04 , ros2 foxy.

**Comment by MichaelOrlov** [comment]
Please use our issue templates for reporting a bug or when creating a new issue.

There is not enough information to even start guessing what is going on.

**Comment by MichaelOrlov** [comment]
- Closing as a stale issue without a response from the author.
