### ISSUE TITLE
need for metapackage

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosbag2#174]
I think there's the need for a sort of a metapackage. This package can then be used conveniently for triggering CI but also be part of the ros2-variants. 

I am thinking about `rosbag2_common_extensions`. Any idea for names?

**Comment by wjwwood** [comment]
What would this "meta" package depend on that `rosbag2` does not?

**Comment by Karsten1987** [comment]
`rosbag2_transport` and `ros2bag` (the cli) are on top of `rosbag2`.

I like @wjwwood's idea of renaming `rosbag2` to something more precise as `rosbag2_core` or `rosbag2_cpp` and introduce `rosbag2` as the meta package. That'd allow for the debian package to be `ros-<version>-rosbag2` which makes a lot of sense to me.

**Comment by wjwwood** [comment]
The only downside is the cpp namespace should really match the package name. So if you want to keep using the rosbag2 namespace I’m cpp it really ought to be in a package of the same name.

**Comment by Karsten1987** [comment]
I am proposing to proceed as follows:

* duplicate `rosbag2` package and rename to `rosbag2_cpp`. 
* adjust code within `rosbag2_cpp` to new name .. include headers, namespace, etc.
* adjust `rosbag2_transport` to use `rosbag2_cpp`.
* cleanup `rosbag2` to only contain a basically empty `CMakeLists.txt` as well as a `package.xml` with all the dependencies listed. 
* add `rosbag2` as dependency to `ros2-variants` - either `ros_core` or `ros_base`

opinions?

**Comment by wjwwood** [comment]
Sounds good to me, I like `rosbag2_cpp` as the API name too.
