### ISSUE TITLE
Bug: Incorrect fractional part of seconds in output from the ` ros2 bag info`

### ISSUE THREAD

**Issue by ljk98116** [ros2/rosbag2#1744]
## Description
Recenty I use `$ ros2 bag info -s mcap xxx.mcap `, it returned different result from the mcap command, aka `mcap info xxx.mcap`

### Expected Behavior
I used mcap command and my own python script, they showed the same result.
![expected result](https://github.com/user-attachments/assets/60e3629a-5f9c-4ba8-916a-b37cb5daae9c)
![expected_result2](https://github.com/user-attachments/assets/a097451b-7815-4d08-91db-763f4e32f815)

### Actual Behavior
But when I used ros2 bag info command, the result can be seen from the picture below:
![err_result](https://github.com/user-attachments/assets/2731eeda-5327-4f08-91a6-5374e142b634)

## To Reproduce
It seems like a ros2 foxy bug.
1. Go to rosbag2/rosbag2_transport/src/rosbag2_transport/formatter.cpp
2. The format_duartion function seems incorrect:
3. Scroll down to line 65 and 77,the code here is:
![code_err](https://github.com/user-attachments/assets/10ebc1c2-9b61-4fcb-8086-9e35013d7b78)
It seems like the front zeros are missed when using std::to_string method to transform the data format, because 1ms is not 0.1s,it should be 0.001s.

## System (please complete the following information)
 - OS: Ubuntu 20.04
 - ROS 2 Distro: foxy
 - Install Method: [APT]
 - Version: [release]

## Additional context
The 65th line of the source code file has bug here.

**Comment by clalancette** [comment]
Foxy went End-of-Life in 2023, so we don't support it anymore.  Please retry your test on one of the supported distributions (http://docs.ros.org/en/rolling/Releases.html), and open a new bug if you can still reproduce it there.

**Comment by MichaelOrlov** [comment]
@clalancette After looking into the code, I can confirm that the same implementation and bug exist on Rolling.
With one remark that we moved this code to the 
https://github.com/ros2/rosbag2/blob/e860f65b62a0e93972d5fd17bdc488dd4b43c204/rosbag2_py/src/rosbag2_py/format_bag_metadata.cpp#L41-L64

I can make a quick fix.

**Comment by MichaelOrlov** [comment]
- Closing as fixed in the #1745 and https://github.com/ros2/rosbag2/pull/1754
