### ISSUE TITLE
Size is 0B when executing "ros2 bag info <db3-file-path>" with file path instead of folder path on any platform with ROS 2 Jazzy

### ISSUE THREAD

**Issue by karthiknit1** [ros2/rosbag2#1756]
## Description
With ROS 2 Jazzy binary installation, when I executed the following command, size of bag file shown is 0 B.

#### D:\jazzy\ros2\src\ros2\rosbag2\rosbag2_tests\resources\sqlite3\cdr_test>ros2 bag info cdr_test_0.db3
[INFO] [1721637334.071023900] [rosbag2_storage]: Opened database 'cdr_test_0.db3' for READ_ONLY.

Files:             cdr_test_0.db3
Bag size:          0 B
Storage id:        sqlite3
ROS Distro:        rolling
Duration:          0.151s
Start:             Apr  9 2020 09:57:36.763 (1586406456.763)
End:               Apr  9 2020 09:57:36.914 (1586406456.914)
Messages:          7
Topic information: Topic: /test_topic | Type: test_msgs/msg/BasicTypes | Count: 3 | Serialization Format: cdr
                   Topic: /array_topic | Type: test_msgs/msg/Arrays | Count: 4 | Serialization Format: cdr
Service:           0
Service information:

whereas the following command shows correct bag file size

#### D:\jazzy\ros2\src\ros2\rosbag2\rosbag2_tests\resources\sqlite3\cdr_test>ros2 bag info .

Files:             cdr_test_0.db3
Bag size:          29.4 KiB
Storage id:        sqlite3
ROS Distro:        unknown
Duration:          0.151s
Start:             Apr  9 2020 09:57:36.763 (1586406456.763)
End:               Apr  9 2020 09:57:36.914 (1586406456.914)
Messages:          7
Topic information: Topic: /array_topic | Type: test_msgs/msg/Arrays | Count: 4 | Serialization Format: cdr
                   Topic: /test_topic | Type: test_msgs/msg/BasicTypes | Count: 3 | Serialization Format: cdr
Service:           0
Service information:

### Expected Behavior

The bag file size is correctly shown with ROS 2 Iron binary installation, both with folder path and file path as follows:

#### D:\iron\ros2\src\ros2\rosbag2\rosbag2_tests\resources\sqlite3\cdr_test>ros2 bag info cdr_test_0.db3
[INFO] [1721636852.701990900] [rosbag2_storage]: Opened database 'cdr_test_0.db3' for READ_ONLY.

Files:             cdr_test_0.db3
Bag size:          28.0 KiB
Storage id:        sqlite3
Duration:          0.151s
Start:             Apr  9 2020 09:57:36.763 (1586406456.763)
End:               Apr  9 2020 09:57:36.914 (1586406456.914)
Messages:          7
Topic information: Topic: /array_topic | Type: test_msgs/msg/Arrays | Count: 4 | Serialization Format: cdr
                   Topic: /test_topic | Type: test_msgs/msg/BasicTypes | Count: 3 | Serialization Format: cdr

#### D:\iron\ros2\src\ros2\rosbag2\rosbag2_tests\resources\sqlite3\cdr_test>ros2 bag info .

Files:             cdr_test_0.db3
Bag size:          29.4 KiB
Storage id:        sqlite3
Duration:          0.151s
Start:             Apr  9 2020 09:57:36.763 (1586406456.763)
End:               Apr  9 2020 09:57:36.914 (1586406456.914)
Messages:          7
Topic information: Topic: /array_topic | Type: test_msgs/msg/Arrays | Count: 4 | Serialization Format: cdr
                   Topic: /test_topic | Type: test_msgs/msg/BasicTypes | Count: 3 | Serialization Format: cdr

## System
 - OS: Windows 11 or any platform
 - ROS 2 Distro: Jazzy
 - Install Method: release archive
 - Version: ROS 2 Jazzy Jalisco Patch Release 1 (2024-07-05)

**Comment by r7vme** [comment]
I'll take a look, I can reproduce it on Linux for sqlite3 storage (for mcap all is fine)
