### ISSUE TITLE
rosbag2_transport cannot be found on Windows

### ISSUE THREAD

**Issue by hidmic** [ros2/rosbag2#179]
## Bug report

**Required Info:**

- Operating System:
  - Windows 10
- Installation type:
  - From sources
- Version or commit hash:
  -  https://github.com/ros2/rosbag2/commit/dc2b161f7f019d595edcac926f227a088ea175e4
- Client library (if applicable):
  - rclpy

#### Steps to reproduce issue

When using the `ros2` command, lots of errors come up:

```
Failed to load entry point 'info': DLL load failed: The specified module could not be found.
The C extension 'c:\j\workspace\ci_windows\ws\install\lib\site-packages\rosbag2_transport\_rosbag2_transport_py.pyd' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'play': DLL load failed: The specified module could not be found.
The C extension 'c:\j\workspace\ci_windows\ws\install\lib\site-packages\rosbag2_transport\_rosbag2_transport_py.pyd' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'record': DLL load failed: The specified module could not be found.
The C extension 'c:\j\workspace\ci_windows\ws\install\lib\site-packages\rosbag2_transport\_rosbag2_transport_py.pyd' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
``` 

Seen on https://ci.ros2.org/job/ci_windows/8300/testReport/junit/ros2topic.test/test_cli/test_cli/ first.

#### Expected behavior
I'd expect no errors.

#### Actual behavior
Errors arise

**Comment by hidmic** [comment]
The problem seems to stem from C extensions being imported at the module level, like [this one](https://github.com/ros2/rosbag2/blob/dc2b161f7f019d595edcac926f227a088ea175e4/rosbag2_transport/rosbag2_transport/__init__.py#L32). That does not play along `colcon` workspaces in Windows. CC @Karsten1987.

**Comment by Karsten1987** [comment]
thanks @hidmic for fixing this!
