### ISSUE TITLE
Sort topics by name when executing `ros2 bag info`

### ISSUE THREAD

**Issue by boxanm** [ros2/rosbag2#1797]
## Description

Currently, when executing ros2 bag info, topics are not ordered alphabetically.
While this is manageable for small bagfiles, we encounter files with hundreds of topics.
Even though we invested time in grouping topics into meaningful namespaces, topics within the same namespace are not gathered together, making the output hard to analyze efficiently.

## Related Issues
It might also be convenient to allow users to sort the output by other criteria, such as topic type or message count.
However, simple alphabetical ordering could become the default option.

[This issue](https://github.com/ros2/rosbag2/issues/51) also seems relevant as moving the console output `ros2 bag info` to the  Python layer would necessarily influence any work on topics ordering.

## Completion Criteria

- `ros2 bag info` outputs topics sorted alphabetically by their names.

**Comment by MichaelOrlov** [comment]
cc: @r7vme It looks like a good simple task.

**Comment by r7vme** [comment]
@MichaelOrlov I'll take a look

**Comment by tmillner21** [comment]
May I work on this issue?

**Comment by r7vme** [comment]
@tmillner21 go ahead :+1:
