### ISSUE TITLE
Move get_storage_identifier and get_bagfile_size into BaseInfoInterface

### ISSUE THREAD

**Issue by zmichaels11** [ros2/rosbag2#197]
As per https://github.com/ros2/rosbag2/pull/184#discussion_r338327221,

these API calls are probably better if defined in `BaseInfoInterface` rather than `BaseIOInterface`.

### Required Changes
- [x] Move `get_storage_identifier` from `BaseIOInterface` to `BaseInfoInterface`
- [x] Move `get_bagfile_size` from `BaseIOInterface` to `BaseInfoInterface`
- [x] Update `SqliteStorage`
- [x] ~Update `ros2/rosbag2_bag_v2`~ Not required

### Dependent PRs
- [x] #184 

### PRs
- [x] #209 - Ready for Review

**Comment by Karsten1987** [comment]
@zmichaels11 are you still working on this?

**Comment by zmichaels11** [comment]
Yes I am, I'll push my branch once I rebase onto master.

**Comment by zmichaels11** [comment]
Addressing `Move get_storage_identifier from BaseInfoInterface to BaseIOInterface` and `Move get_bagfile_size from BaseInfoInterface to BaseIOInterface` in PR: https://github.com/ros2/rosbag2/pull/209

**Comment by zmichaels11** [comment]
Removed requirement `remove get_metadata` due to bug resolved by #210.

As per https://github.com/ros2/rosbag2/pull/210#issuecomment-555275503, we should probably discuss on handling `get_metadata` since its required by bagfiles not written by `Writer`.

**Comment by zmichaels11** [comment]
Remove `get_metadata` was moved into https://github.com/ros2/rosbag2/issues/213 due to being more complex and requiring planning.

**Comment by zmichaels11** [comment]
Corrected the tasks in OP;
'get_storage_identifier` and `get_bagfile_size` now correctly state that they're moving INTO `BaseInfoInterface`
