### ISSUE TITLE
github actions fail

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosbag2#235]
@thomas-moulard I've seen that the github actions for the linters all fail. Do you have an idea on why that would be?

see: https://github.com/ros2/rosbag2/pull/230 and https://github.com/ros2/rosbag2/pull/225

**Comment by piraka9011** [comment]
We're working on it, see [ros-security/aws-oncall#31](https://github.com/ros-security/aws-oncall/issues/31).

**Comment by piraka9011** [comment]
This issue has been resolved by the GH team.
https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122/page/2
