### ISSUE TITLE
Remove requirement for ros1-bridge for ros2 bag command

### ISSUE THREAD

**Issue by kellyprankin** [ros2/rosbag2#242]
Is there any timeline on removal of the need for having ros1 installed to use the ros2 bag command?

**Comment by Karsten1987** [comment]
Can you elaborate a bit on where you see this dependency? The only package which depends on the ros1 bridge is the [rosbag2_bag_v2_plugin](https://github.com/ros2/rosbag2_bag_v2).

The current packages within this repo are independent of the bridge.

**Comment by kellyprankin** [comment]
Maybe I am incorrect. When I try to install the ros2 bag command it says that it depends on the ros1-bridge. Did I install the wrong one?

**Comment by Karsten1987** [comment]
It depends how you installed your packages. All packages you find on the eloquent branch of this repo can be installed via apt on your Linux system. 
If you have installed all packages based on a ‘rosbag2’ prefix you most likely also installed the before mentioned plugin for ros1 bag files.

**Comment by kellyprankin** [comment]
@Karsten1987 The instructions at https://github.com/ros2/rosbag2 say to do:

 sudo apt-get install ros-eloquent-ros2bag* ros-eloquent-rosbag2*

**Comment by Karsten1987** [comment]
This way will install all packages including the ros1 bridge related one. 
In order to avoid that you have to install the individual packages by hand for now. That is:
ros-eloquent-rosbag2-transport and ros-eloquent-ros2bag 

We are currently working making this easier and the ros1 bridge related one really only optional: #241

**Comment by kellyprankin** [comment]
Thanks for talking me through it.  I'll give that a shot

**Comment by kellyprankin** [comment]
Your solution worked for me. I am hoping I can get them to update the documentation for the ROS2 Tutorial, because it isn't clear that you can avoid the issue. Thanks again

**Comment by dirk-thomas** [comment]
> I am hoping I can get them to update the documentation for the ROS2 Tutorial, because it isn't clear that you can avoid the issue.

The instructions are in the README file in this repo: https://github.com/ros2/rosbag2/blob/master/README.md

@kellyprankin Please consider to propose a pull request to improve the instructions.
