### ISSUE TITLE
Allow plugins to register their own CLI verb arguments

### ISSUE THREAD

**Issue by piraka9011** [ros2/rosbag2#276]
## Description

Provide a way for rosbag2 plugins to extend the CLI verb arguments. This can be handled with `--storage-config-uri` for play and record, but there is an advantage to a file-free invocation. These options would need to be added only when the plugin is actually in use for e.g. play/record, or other verbs.

## Implementation notes

The flow of data may be a little awkward for this - since most plugins are loaded after arguments are fully parsed, often based on the CLI arguments themselves.

For example `ros2 bag play` takes in a URI and optional storage ID, and uses that information to find the correct storage implementation to use for playing. To retrieve more arguments, the CLI would need to first see the `--storage` option, open that plugin, ask it to extend the ArgumentParser, then continue parsing arguments. This may not be impossible, but perhaps a little unwieldy.

How would users know to find these options? Maybe `ros2 bag play --help --storage mcap` to append extra options for that storage implementation?

# Original issue text for context

Original request in #152:

> Options for different compression algorithms - allows trading off size & speed or using algorithms designed for specific types of data (like image compression on an image topic).

-----

A potential approach is creating a new compression options struct that compression formats can extend with their own specific configurations.
An example for zstd would be the compression level.
This would require parsing the input from the CLI and making sure that the options match the format specified by the user (e.x. only zstd configurations work with the `--compression-format zstd` flag)

**Comment by MichaelOrlov** [comment]
- Closing as resolved in #1209.
- @emersonknapp @piraka9011 Feel free to reopen if #1209 doesn't fully address problem described in this issue.
