### ISSUE TITLE
Loop playback

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#292]
## Description

When playing back a bagfile, I would like to be able to specify a commandline option so that it starts back at the beginning on reaching the end, and plays indefinitely.

## Related Issues

N/A

## Completion Criteria

* [ ] A user can specify a commandline option to loop playback indefinitely

## Implementation Notes / Suggestions

none

## Testing Notes / Suggestions

none

**Comment by ketatam** [comment]
Hi, I am starting to work on this issue.

**Comment by ketatam** [comment]
Hi, is it okay that we reopen the database every time we reach the end and replay the bagfile or do we have to only open it once at the beginning? Thank you!
