### ISSUE TITLE
Github build action failure

### ISSUE THREAD

**Issue by zmichaels11** [ros2/rosbag2#293]
## Description
The periodic build of `rosbag2` is currently [failing](https://github.com/ros2/rosbag2/commit/06de965fdc21ab5040240f2fb517358b136e5549/checks?check_suite_id=453793241).
The logs suggest that its from an upstream change in `fastrtps`.

---
Opening an issue on [aws-oncall](https://github.com/ros-tooling/aws-oncall/issues/73)

**Comment by emersonknapp** [comment]
This is fixed :)
