### ISSUE TITLE
Document QoS profile override behavior in Wiki tutorial

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#357]
## Description

https://index.ros.org/doc/ros2/Tutorials/Ros2bag/Recording-And-Playing-Back-Data/ describes how to use rosbag2.

Update it to thoroughly document how to specify QoS overrides, and update the note in ros2bag to point to the wiki page.

## Related Issues

#125

**Comment by Karsten1987** [comment]
Additionally to the tutorial (which is great idea btw), I think we should also enhance the `readme.md` in this repo to reflect the new changes.

**Comment by emersonknapp** [comment]
Agreed
