### ISSUE TITLE
rosbag2 fails with opensplice

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros2/rosbag2#36]
For rosbag2, we currently rely on subscribing serialized messages. 
`rmw_opensplice` seems to not yet implement those functions in a working state.

**Comment by Karsten1987** [comment]
There's an open ticket on the opensplice github:
https://github.com/ADLINK-IST/opensplice/issues/50

Until there is support for getting serialized data, this is a `won't-fix` issue.

**Comment by dirk-thomas** [comment]
Can this be closed?

**Comment by emersonknapp** [comment]
Yes!
