### ISSUE TITLE
Windows test_rosbag2_record_end_to_end test failure

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#380]
## Description

The following tests are failing persistently on Windows CI builds

* record_end_to_end_with_splitting_bagsize_split_is_at_least_specified_size
* record_end_to_end_with_splitting_splits_bagfile

https://ci.ros2.org/view/nightly/job/nightly_win_deb/1613/testReport/junit/rosbag2_tests/RecordFixture/record_end_to_end_with_splitting_bagsize_split_is_at_least_specified_size/

## System
 - OS: Ubuntu Focal
 - ROS 2 Distro: Foxy
 - Version: master, reporting as of 9909f8c3fd307d4

## Extra Context

It looks like the bagfiles are not splitting as expected when running on windows, but the Linux tests aren't even checking this condition because it is #ifdeffed out, it may be incorrect on Linux as well.

**Comment by wjwwood** [comment]
> The following tests are failing persistently on Windows CI builds

> OS: Ubuntu Focal

Is this wrong? Btw, this test seems to timeout on Linux too:

https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_debug/1196/testReport/(root)/projectroot/test_rosbag2_play_end_to_end/

**Comment by wjwwood** [comment]
Sorry, what I linked to is the `play` version, whereas this one is reporting the `record` one I think.

**Comment by emersonknapp** [comment]
Yeah - that's right. It seems that `play_end_to_end` is now timing out on all platforms - not sure when exactly that started.

**Comment by mm318** [comment]
Looks like https://github.com/ros2/rosbag2/pull/407 has possibly fixed this issue.

[Build 1618](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1618/testReport/rosbag2_tests/RecordFixture/) was the last failing build. This issue has been fixed in [build 1620](https://ci.ros2.org/view/nightly/job/nightly_win_deb/1620/testReport/rosbag2_tests/RecordFixture/).
