### ISSUE TITLE
Delete empty bag file on record error

### ISSUE THREAD

**Issue by greimela-si** [ros2/rosbag2#39]
It would be nice to clean up empty bag files if `ros2 bag record` fails to start or terminates before recording any messages.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-tooling-wg-next-meeting/12545/33

**Comment by emersonknapp** [comment]
closing as stale - rosbag2 currently does not create bag files for most bad start-up situations, and it may be desirable to at least maintain the metadata of an empty recording that received no messages.

Please reopen if there is a specific case that should be handled.
