### ISSUE TITLE
make rosbag2 related packages relocatable

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rosbag2#402]
Atm various `.cmake` files installed by `rosbag2_*` packages and its dependencies contain absolute paths to the install space which makes them non-relocatable. See:

* https://github.com/ros2/ros2/issues/915#issuecomment-623552072
* https://github.com/ros2/ros2/issues/904

**Comment by dirk-thomas** [comment]
FYI https://github.com/ros2/console_bridge_vendor/pull/9#discussion_r419693928

**Comment by Karsten1987** [comment]
With the referenced PRs, the exported cmake targets look good now for rosbag2_transport (the highest package in the hierarchy):

```
set_target_properties(rosbag2_transport::rosbag2_transport PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "rcl::rcl;rclcpp::rclcpp;rcutils::rcutils;rmw::rmw;rosbag2_compression::rosbag2_compression;rosbag2_compression::rosbag2_compression_zstd;rosbag2_cpp::rosbag2_cpp;shared_queues_vendor::singleproducerconsumer;shared_queues_vendor::concurrentqueue;yaml-cpp"
)
```

**Comment by Karsten1987** [comment]
Isolated packaging job:
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=1852)](https://ci.ros2.org/view/packaging/job/packaging_linux/1852/)

**Comment by Karsten1987** [comment]
new round of CI:
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=packaging_linux&build=1856)](https://ci.ros2.org/view/packaging/job/packaging_linux/1856/)

**Comment by Karsten1987** [comment]
So I downloaded the package job linked above and looked at the content of exported cmake files of rosbag2_transport.

```
set_target_properties(rosbag2_transport::rosbag2_transport PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "rcl::rcl;rclcpp::rclcpp;rcutils::rcutils;rmw::rmw;rosbag2_compression::rosbag2_compression;rosbag2_compression::rosbag2_compression_zstd;rosbag2_cpp::rosbag2_cpp;shared_queues_vendor::singleproducerconsumer;shared_queues_vendor::concurrentqueue;yaml-cpp"
)
```

So there's no absolute path in it which makes me believe it's in a decent state. I can't really use it locally on my machine as I don't have a Focal installation at hand. If somebody could verify that the packages are indeed now relocatable, that'd be great.

@dirk-thomas maybe you could have a look at this. I am deliberately not running a full set of CI yet because I want to rule out that a) this is actually needed and b) what kind of jobs I should run. I could imagine that it could make sense to run a debug/release job to make sure that the imported libraries are correctly set.

Opinions?

**Comment by dirk-thomas** [comment]
> maybe you could have a look at this.

Please try it in a Focal VM or a Docker container instead.

> I am deliberately not running a full set of CI yet because I want to rule out that a) this is actually needed and b) what kind of jobs I should run.

At least a build on all platforms makes sense.

**Comment by Karsten1987** [comment]
CI, building all, testing `rosbag2_transport`.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10640)](http://ci.ros2.org/job/ci_linux/10640/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6070)](http://ci.ros2.org/job/ci_linux-aarch64/6070/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8663)](http://ci.ros2.org/job/ci_osx/8663/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10548)](http://ci.ros2.org/job/ci_windows/10548/)

**Comment by dirk-thomas** [comment]
You might want to test all packages touched in order to run their linters.

**Comment by Karsten1987** [comment]
building all, testing `rosbag2_storage rosbag2_transport rosbag2_cpp rosbag2_test_common rosbag2_tests pluginlib tinyxml2_vendor yaml_cpp_vendor rviz_common`
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10642)](http://ci.ros2.org/job/ci_linux/10642/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6071)](http://ci.ros2.org/job/ci_linux-aarch64/6071/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8664)](http://ci.ros2.org/job/ci_osx/8664/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10549)](http://ci.ros2.org/job/ci_windows/10549/)

**Comment by Karsten1987** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10727)](http://ci.ros2.org/job/ci_linux/10727/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6132)](http://ci.ros2.org/job/ci_linux-aarch64/6132/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8735)](http://ci.ros2.org/job/ci_osx/8735/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10619)](http://ci.ros2.org/job/ci_windows/10619/)

**Comment by Karsten1987** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10734)](http://ci.ros2.org/job/ci_linux/10734/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6136)](http://ci.ros2.org/job/ci_linux-aarch64/6136/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8739)](http://ci.ros2.org/job/ci_osx/8739/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10625)](http://ci.ros2.org/job/ci_windows/10625/)

**Comment by Karsten1987** [comment]
I think this is good to go for a review.

**Comment by dirk-thomas** [comment]
Please enumerate the PRs included in the above CI builds.

**Comment by Karsten1987** [comment]
It includes all the ones which are linked here to this ticket.


https://github.com/ros2/rosbag2/pull/403
https://github.com/ros2/tinyxml2_vendor/pull/8
https://github.com/ros2/yaml_cpp_vendor/pull/9
https://github.com/ros/pluginlib/pull/190
https://github.com/ros2/rviz/pull/542

**Comment by Karsten1987** [comment]
Another round of CI with the latest changes from #403 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10765)](http://ci.ros2.org/job/ci_linux/10765/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6157)](http://ci.ros2.org/job/ci_linux-aarch64/6157/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8763)](http://ci.ros2.org/job/ci_osx/8763/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10654)](http://ci.ros2.org/job/ci_windows/10654/)

**Comment by Karsten1987** [comment]
My only explanation for the windows build failure is that the package wasn't rebased correctly - it passes locally in my VM:

another shot: 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10768)](http://ci.ros2.org/job/ci_linux/10768/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6160)](http://ci.ros2.org/job/ci_linux-aarch64/6160/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8766)](http://ci.ros2.org/job/ci_osx/8766/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10658)](http://ci.ros2.org/job/ci_windows/10658/)

**Comment by Karsten1987** [comment]
After [RViz magic](https://github.com/ros2/rviz/pull/542/commits/b44d6606cd10ea217935e101bc2d06f3955cb8d7), another round of CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10785)](http://ci.ros2.org/job/ci_linux/10785/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6170)](http://ci.ros2.org/job/ci_linux-aarch64/6170/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8776)](http://ci.ros2.org/job/ci_osx/8776/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10673)](http://ci.ros2.org/job/ci_windows/10673/)

**Comment by Karsten1987** [comment]
RViz magic, part two, another round of CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10791)](http://ci.ros2.org/job/ci_linux/10791/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6176)](http://ci.ros2.org/job/ci_linux-aarch64/6176/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8783)](http://ci.ros2.org/job/ci_osx/8783/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10679)](http://ci.ros2.org/job/ci_windows/10679/)

**Comment by Karsten1987** [comment]
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10833)](http://ci.ros2.org/job/ci_linux/10833/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6208)](http://ci.ros2.org/job/ci_linux-aarch64/6208/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8824)](http://ci.ros2.org/job/ci_osx/8824/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10719)](http://ci.ros2.org/job/ci_windows/10719/)

**Comment by Karsten1987** [comment]
repos file was outdated:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10839)](http://ci.ros2.org/job/ci_linux/10839/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6212)](http://ci.ros2.org/job/ci_linux-aarch64/6212/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8830)](http://ci.ros2.org/job/ci_osx/8830/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10723)](http://ci.ros2.org/job/ci_windows/10723/)
