### ISSUE TITLE
cache based on elapsed recording time

### ISSUE THREAD

**Issue by adamdbrw** [ros2/rosbag2#424]
## Description

The current version of `--max-cache` parameter for bag recording allows to specify a number of messages to include per cache (Or transaction, with SQLite backend).

I believe that it is better to specify how many seconds of data to cache instead. This is far easier to understand in terms of user experience ("I will lose at most a second of data if there is a crash") and not dependent on number and rates of topics. 

I also suggest to change the default value from 0 to 1s. Zero is really bad for performance with SQLite backend, since it results in transaction for every single message (Implicitly, in SQLite). The default should be such that it behaves well for most cases.  

## Implementation Notes / Suggestions

The parameter `--max-cache` could be extended to interpret both "1" and "1s" type of arguments.

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-tooling-wg-next-meeting/12545/33
