### ISSUE TITLE
Invalid splitting size exception not handled when using splitting+compression together

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros2/rosbag2#432]
### Expected Behavior
When an invalid value is passed for split bag size in `ros2 bag record -b <size>`, an `InvalidArgument` exception is thrown. This exception is not handled correctly when using compression with splitting, and the process crashes.

For example, using macOS + FastRTPS:
```bash
➜  ~ ros2 bag record -a -b 50000 --compression-mode file --compression-format zstd
[INFO] [1591314011.630700641] [rosbag2_storage]: Opened database 'rosbag2_2020_06_04-16_40_11/rosbag2_2020_06_04-16_40_11_0.db3' for READ_WRITE.
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Invalid bag splitting size given. Please provide a different value.
[1]    83688 abort      ros2 bag record -a -b 50000 --compression-mode file --compression-format zstd
```
The process crashes.

Works as expected when compression options are dropped:
```bash
➜  ~ ros2 bag record -a -b 50000
[INFO] [1591314636.517055206] [rosbag2_storage]: Opened database 'rosbag2_2020_06_04-16_50_36/rosbag2_2020_06_04-16_50_36_0.db3' for READ_WRITE.
[ERROR] [1591314636.517268743] [rosbag2_transport]: Failed to record: Invalid bag splitting size given. Please provide a different value.
```

### Actual Behavior
The exception should be handled correctly even when compression is enabled.

## To Reproduce
Run `ros2 bag record -a -b 50000 --compression-mode file --compression-format zstd`

## System (please complete the following information)
 - OS: macOS 10.14, Windows server 2019
 - ROS 2 Distro: Foxy
 - Version: Prerelease fat binary

**Comment by emersonknapp** [comment]
AWS team picking this up for planned completion by next WG meeting
