### ISSUE TITLE
Configuration for sqlite

### ISSUE THREAD

**Issue by adamdbrw** [ros2/rosbag2#437]
## Description

SQLite mode settings such as "journal mode", "synchronous" (and other) can have a very significant effect on performance. Current settings are hardcoded in sqlite_wrapper.cpp and promote reliability at the cost of increased overheads. This should be configurable by user e.g. through a config file.

## Related Issues

This issue comes from performance testing of rosbag2 #435.

## Implementation Notes / Suggestions

A .yaml file can be used, with one section containing anything that would be executed as a PRAGMA statement on database creation or just a whitelisted set. This file content should be read and then applied by SqliteWrapper (in ctor). Other settings (i.e. not PRAGMA statements) should also be possible to add. An example would be whether an index is created right away or when inserts finish. 

## Testing Notes / Suggestions
- Use #435 packages (soon to come) to confirm performance change
- Run rosbag2_tests
- With various journal mode settings, attempt to cause a crash during recording

**Comment by adamdbrw** [comment]
Attachment: 

A patch and config file from a hacky solution I used to test different settings. Of course implementation should be different, but this could be useful to kickstart:

[config_reading_hacky.zip](https://github.com/ros2/rosbag2/files/4781614/config_reading_hacky.zip)

**Comment by adamdbrw** [comment]
Changing SQLite configuration through a feature enabled by this enhancement would be the fastest way to improve performance dramatically (using settings journal_mode=MEMORY and synchronous=OFF).

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros2-tooling-wg-next-meeting/12545/33
