### ISSUE TITLE
fix troubleshooting URL

### ISSUE THREAD

**Issue by dirk-thomas** [ros2/rosbag2#445]
Since the page was moved in ros2/ros2_documentation#700. Same as ros2/rclpy#579

See https://github.com/ros2/rosbag2/blob/e9d006b6a88bddc42b5a167e121a8fc950f6cced/rosbag2_transport/rosbag2_transport/__init__.py#L33

Instead of fixing the URL in the code I suggest to deduplicate this copied logic with the one existing in `rclpy` and make the functionality reusable instead.

The fix needs to be backported to all active distros.

**Comment by emersonknapp** [comment]
AWS team picking this up for planned completion by next WG meeting
