### ISSUE TITLE
How to write data to rosbag2 with API

### ISSUE THREAD

**Issue by henry0572** [ros2/rosbag2#449]
## Description
It is not possible to write data directly to rosbag2 using ros2 foxy.
I get the same error as below.

[ROS2]How to write data to rosbag2 in ros2 foxy
https://answers.ros.org/question/355764/ros2how-to-write-data-to-rosbag2-in-ros2-foxy/

I was able to load the data based on the following.

How to read data from rosbag2 in ros2
https://stackoverflow.com/questions/60282296/how-to-read-data-from-rosbag2-in-ros2

### Expected Behavior
Writing succeeds.

### Actual Behavior

`writer.write(message)` is what cause all the error messages:
```
terminate called after throwing an instance of 'std::logic_error' what(): basic_string::_M_construct null not valid
```

## System
 - OS: Ubunutu 20.04
 - ROS 2 Distro: Foxy
 - Version: release

**Comment by emersonknapp** [comment]
@henry0572 thanks for bringing this up. The C++ API is not straightforward. You can see in @Karsten1987 's PR ^ linked above this comment, a project to reduce the complexity of using the C++ API directly. It also acts as a good example of how to use it as it is currently.

**Comment by Karsten1987** [comment]
The following test should illustrate how to use the C++ API as of now. There will be further modifications done which allows users to directly write non-serialized messages in the future. 
https://github.com/ros2/rosbag2/blob/master/rosbag2_tests/test/rosbag2_tests/test_rosbag2_cpp_api.cpp

I'll go ahead and close this issue as it's possible to write data to rosbag2 via the C++ API.
