### ISSUE TITLE
ros2bag QOS test uses several sleeps on windows

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosbag2#454]
Test is "reliably" failing on windows:
https://ci.ros2.org/view/nightly/job/nightly_win_rel/1605/testReport/ros2bag.test/test_record_qos_profiles/test_record_qos_profiles/

```
FAIL: test_record_qos_profiles.TestRos2BagRecord.test_incomplete_qos_profile
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python38\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\tmphur3j5pi\\ros2bag_test_incomplete_0.db3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\tempfile.py", line 803, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\tmphur3j5pi\\ros2bag_test_incomplete_0.db3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ci\ws\src\ros2\rosbag2\ros2bag\test\test_record_qos_profiles.py", line 87, in test_incomplete_qos_profile
    assert not matches, print('ros2bag CLI did not produce the expected output')
```

@emersonknapp do you have an idea?

**Comment by emersonknapp** [comment]
I don't know immediately but will begin investigating

**Comment by dirk-thomas** [comment]
@emersonknapp Any update on this?

**Comment by dirk-thomas** [comment]
Please see #462 which modifies the test to only create one temp dir for all tests within the test class. That allows it to be cleanly removed on Windows.

**Comment by dirk-thomas** [comment]
The test is still failing (even though it passed CI on the PR) - reopening...

**Comment by emersonknapp** [comment]
Noted - we are pulling this in as top priority for Monday

**Comment by jaisontj** [comment]
@dirk-thomas Could you take a look at: #525 ? It gets rid of most of the `time.sleep` except for the one inside `tearDownClass`. Was not able to find a better way around it. However, given the title of this issue, we no longer use several sleeps in the test, can this issue be closed?

**Comment by dirk-thomas** [comment]
> can this issue be closed?

Sounds good to me. Once the PR is merged that should happen automatically.
