### ISSUE TITLE
ros2 bag record (foxy version) not able to record the topics (dashing version)

### ISSUE THREAD

**Issue by pulkitgoyal1506** [ros2/rosbag2#474]
## Description
In my setup, I have two PCs on a LAN. PC-1 has the ROS (dashing version) running on it with topics publishing some data. PC-2 has the ROS (foxy version) running on it with recorder recording PC-1 data. I am recording data published on the topics of PC-1, using rosbag recorder on PC-2.

### Expected Behavior
I expect the recorder running ros foxy version to record the data being published from ros dashing version. Foxy is only able to list the topics from dashing and is unable to record, echo or hz them.

### Actual Behavior
Foxy bag recorder is not recording any data coming from dashing topics. Executing 'ros2 topic list' on PC-2 is listing all the topics running on PC-1. But 'ros2 bag record', 'ros2 topic hz' or 'ros2 topic echo' is not subscribing to any of those topics.

Output of ros2 bag record command on PC-2:
![image](https://user-images.githubusercontent.com/36778203/88713225-cc24e880-d0cf-11ea-9743-ad814cf2dfc0.png)

## To Reproduce

- PC1 with ROS2 dashing publishing data on some topics
- PC2 with ROS2 foxy recording data from PC-1

## System
- PC1: ROS 2 Dashing, Ubuntu 18.04
- PC2: ROS 2 Foxy, Ubuntu 20.04

**Comment by emersonknapp** [comment]
This is a consequence of the underlying ROS 2 communication infrastructure. Rosbag2 just uses subscriptions to receive messages, so it's limited to that behavior. I think that this would be better filed against github.com/ros2/ros2 - I don't think there's anything that can be done about it here.

**Comment by pulkitgoyal1506** [comment]
Thanks for quick response. I have raised an issue on ros2 repository, closing it here.
