### ISSUE TITLE
rosbag2 memory leak

### ISSUE THREAD

**Issue by dawonn-haval** [ros2/rosbag2#499]
## Description
I was running `my_test_plugin` with a debug trace as described in #498 overnight; when I returned in the morning the node was killed by the kernel for consuming all of the memory in the system.

![image](https://user-images.githubusercontent.com/44446780/89710416-dc02bf00-d950-11ea-881b-379a6cdb5c2e.png)

### Expected Behavior
No memory leaks.

## System
 - OS: U20.04
 - ROS 2 Distro: Foxy
 - Version: master (f1d1145de6762)
 - RMW: fastrtps (Default Settings)

## Additional context
I was attempting to track down why lidar and image topics stop (and apparently restart) recording. Here is the final output of the trace from #498:
![image](https://user-images.githubusercontent.com/44446780/89710481-6814e680-d951-11ea-926b-0fcada51c041.png)

**Comment by Stapelzeiger** [comment]
What RMW are you using?

**Comment by dawonn** [comment]
Default: fastrtps

**Comment by dawonn-haval** [comment]
Perhaps interesting note: if I run rosbag2 in valgrind I never receive any messages from the 'large' topics. If I stop and run without valgrind, i do receive them.

**Comment by dawonn-haval** [comment]
https://github.com/ros2/rosbag2/blob/f1d1145de6762ec0d3d19246f7a374ffdd4441fe/rosbag2_transport/src/rosbag2_transport/recorder.cpp#L170

It's not so much that rcl expects the client to deconstruct the message, but rosbag2 explicitly takes ownership of the data there. I'm still trying to figure out how the destructor is called. I expected to see rmw_serialized_message_fini() be called, but don't see any references to it. Might be on to something?

**Comment by Karsten1987** [comment]
I could see that there's indeed a bug introduced in [this PR](https://github.com/ros2/rosbag2/pull/386/files). 
As @dawonn pointed out we transfer ownership via `release_rcl_serialized_message()`, but the bag message doesn't clean up the serialized message. 
The likely fix for this is to replace the `std::make_shared` call with a instantiation of that shared pointer with a custom destructor which cleans up the buffer.

**Comment by Karsten1987** [comment]
see https://github.com/ros2/rosbag2/pull/502 for a potential fix. Any feedback on the PR is welcome.

**Comment by Karsten1987** [comment]
closed via #502
