### ISSUE TITLE
rosbag2_py build failure in clang+libcxx nightly builds

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#505]
## Description
Context https://github.com/ros2/rosbag2/pull/308#issuecomment-674079102

## Additional context
Introduced in https://github.com/ros2/rosbag2/pull/308

**Comment by mabelzhang** [comment]
Just adding a note to summarize progress so far.
We got past the compiler failure by adding #pragma lines (my code is in `fix_issue_505_linux`). But now we have test failures:
https://ci.ros2.org/job/ci_linux/11953
```
>       reader.open(storage_options, converter_options)
E       RuntimeError: No storage could be initialized. Abort

../test/test_sequential_reader.py:30: RuntimeError

----------------------------- Captured stderr call -----------------------------
[ERROR] [1597438853.854357985] [rosbag2_storage]: Unable to load instance of read write interface: Could not create instance of type rosbag2_storage_plugins::SqliteStorage
[ERROR] [1597438853.854392941] [rosbag2_storage]: Could not load/open plugin with storage id 'sqlite3'.
```

I am not sure what is causing the error. Seems a C++ exception?

A workaround, if we want to remove the `AMENT_IGNORE` file quickly, is to disable to test for Clang for now, which I've already done in the branch here and tested it makes CI green ( https://ci.ros2.org/job/ci_linux/11957/ ):
https://github.com/ros2/rosbag2/blob/fix_issue_505_linux/rosbag2_py/CMakeLists.txt#L61

Now that I look at it again, maybe it shouldn't have the GNUCXX part, then the line would be just:
```
if(BUILD_TESTING AND NOT (CMAKE_CXX_COMPILER_ID MATCHES "Clang"))
```
