### ISSUE TITLE
Remove printing of console output from rosbag2_transport

### ISSUE THREAD

**Issue by anhosi** [ros2/rosbag2#51]
Currently the `ros2 bag info` output is created directly in `rosbag2_transport`. This should change and the console output should happen in the python layer above.

**Comment by MichaelOrlov** [comment]
- Closing as wouldn't be done.
We are trying to keep the Python layer as a thin wrapper around the C++ layer, and I don't envision any rationale for moving some implementation details out of the C++ layer.
