### ISSUE TITLE
👩‍🌾 End-to-end tests are flaky

### ISSUE THREAD

**Issue by chapulina** [ros2/rosbag2#513]
## Description

Several `end_to_end` tests are flaky.

### Expected Behavior

All tests should pass consistently.

### Actual Behavior

They fail sometimes.

## To Reproduce

Check their histories in the nightly builds:

* [test_rosbag2_record_end_to_end on windows](https://ci.ros2.org/job/nightly_win_rep/1973/testReport/(root)/projectroot/test_rosbag2_record_end_to_end/history/): Failed 1 / 18 last builds
* [test_rosbag2_play_end_to_end on osx](https://ci.ros2.org/job/nightly_osx_repeated/2066/testReport/(root)/projectroot/test_rosbag2_play_end_to_end/history/): Failed 3 / 22 last builds
* [test_rosbag2_record_end_to_end on osx](https://ci.ros2.org/job/nightly_osx_repeated/2069/testReport/(root)/projectroot/test_rosbag2_record_end_to_end/history/): Failed 5 / 22 last builds
* [test_rosbag2_info_end_to_end on osx](https://ci.ros2.org/job/nightly_osx_repeated/2069/testReport/(root)/projectroot/test_rosbag2_info_end_to_end/history/): Failed only the latest build - possible regression

If these can't be solved quickly, consider disabling them.

**Comment by emersonknapp** [comment]
We will mark these as xfail for now - we need to make architectural changes to make these tests more deterministic

**Comment by MichaelOrlov** [comment]
@emersonknapp Do you remember what was the root cause or error messages for flaky tests?

**Comment by emersonknapp** [comment]
Unfortunately, I don't remember any details. I think in general, subscribers would not receive the number of expected messages. This would happen sometimes from slow discovery, or shutdown edge cases. But I am not sure if that description covers all cases that were observed.
