### ISSUE TITLE
Cannot list all storage plugin

### ISSUE THREAD

**Issue by Barry-Xu-2018** [ros2/rosbag2#553]
## Description
Cannot list all storage plugin

### Expected Behavior
List all storage plugin
$ ros2 bag list storage
sqlite3
my_test_plugin
my_read_only_test_plugin

### Actual Behavior
Not list `my_read_only_test_plugin` plugin
$ ros2 bag list storage
sqlite3
my_test_plugin

The contents for install/rosbag2_storage/share/rosbag2_storage/test/rosbag2_storage/test_plugin.xml
```xml
<library path="test_plugin">
  <class
    name="my_test_plugin"
    type="TestPlugin"
    base_class_type="rosbag2_storage::storage_interfaces::ReadWriteInterface"
  >
    <description>This is a test storage plugin.</description>
  </class>

  <class
    name="my_read_only_test_plugin"
    type="TestReadOnlyPlugin"
    base_class_type="rosbag2_storage::storage_interfaces::ReadOnlyInterface"
  >
    <description>This is a read-only test storage plugin.</description>
  </class>
</library>
```
Now it only lists first plugin in test_plugin.xml

## To Reproduce
** Steps to reproduce the behavior, e.g.
$ ros2 bag list storage

## System (please complete the following information)
 - OS: Ubuntu focal
 - ROS 2 Distro: rolling
 - Version: master

**Comment by Karsten1987** [comment]
closing through https://github.com/ros2/rosbag2/pull/554
