### ISSUE TITLE
Support for regex in defining recorded topics

### ISSUE THREAD

**Issue by TimoKettunen** [ros2/rosbag2#559]
## Description
rosbag2 command should have an option -e to allow defining recording topics that match regular expression.
ROS(1) has this feature, ROS2 should have parity with ROS, See http://wiki.ros.org/rosbag/Commandline.
## Related Issues
None

## Completion Criteria
giving command 
```
$ ros2 bag record -e "<regex>" 
```
records all topics that match the regex

**Comment by emersonknapp** [comment]
This sounds like a neat feature!

**Comment by adamdbrw** [comment]
Agreed, at least a couple of times I needed this as well

**Comment by adamdbrw** [comment]
@TimoKettunen, @emersonknapp  turns out this would be very useful for our benchmarking package, so I submitted a PR draft. Hopefully this feature will soon be available.

**Comment by adamdbrw** [comment]
This is resolved with #604
