### ISSUE TITLE
Support for excluding topics

### ISSUE THREAD

**Issue by TimoKettunen** [ros2/rosbag2#560]
## Description
rosbag2 command should have an option -x to allow excluding recording topics that match regular expression.
ROS(1) has this feature, ROS2 should have parity with ROS, See http://wiki.ros.org/rosbag/Commandline.
## Related Issues
None

## Completion Criteria
giving command 
```
$ ros2 bag record -a -x "<regex>" 
```
records all topics except those that match the regex

## Testing Notes / Suggestions

**Comment by emersonknapp** [comment]
Yes, confirmed that this is a feature gap. PRs welcome, not sure when we'll have bandwidth to take this on at the moment. It shouldn't be too difficult, probably a good first issue for someone.

**Comment by adamdbrw** [comment]
This is resolved with #604
