### ISSUE TITLE
cmake 3.19.1 deprecated a policy for cmake versions < 2.8.12

### ISSUE THREAD

**Issue by brawner** [ros2/rosbag2#573]
With a recent update to cmake, a policy which whose behavior was split in 2.8.12 has now been deprecated (see https://cmake.org/cmake/help/latest/policy/CMP0022.html for information). This causes a regular warning for windows builds on ci.ros2.org because those jobs are always downloading the latest version of cmake.

I submitted a PR to `zstd`, which was accepted and merged to update the cmake version. However, I'm not sure when it will get released. When it becomes available, `zstd_vendor` may want to update it's release version.

Upstream PR
https://github.com/facebook/zstd/pull/2399

**Comment by emersonknapp** [comment]
Looks like they've been releasing every ~6mo or so... so hopefuly we're due for a new release soon! We're currently using 1.4.4 - we could upgrade to 1.4.5 but yeah that wouldn't get us the CMake fix.

In the meantime, we could apply a patch to the ExternalProject just to make the CMake warning go away - we do similarly with other vendor projects.
