### ISSUE TITLE
Test failures on Linux-armhf 

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2/rosbag2#574]
## Description

When running CI for the upcoming Dashing patch release I noticed some rosbag2 test failures on armhf.
rosbag2 has not changed in this patch release and armhf is not a full tier 1 platfomr so the issue isn't blocking anything, but it may indicate issues with armhf that cannot be tested on mainline with our current infrastructure.

### Test failures
* rosbag2_transport.FormatterTestFixture.format_file_size_returns_correct_format
* rosbag2_tests.RecordFixture.record_end_to_end_test
* rosbag2_tests.InfoEndToEndTestFixture.info_end_to_end_test

## To Reproduce

This CI job scoped to rosbag2_transport and rosbag2_tests should reproduce the issue [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux-armhf&build=83)](https://ci.ros2.org/job/ci_linux-armhf/83/)

## System
 - OS: Ubuntu Bionic
 - ROS 2 Distro: Dashing
 - Version: 0.1.8

**Comment by emersonknapp** [comment]
Note: we should take a look at this - armhf failures generally indicate a real bug/portability issue. But since it's not a target of Galactic, we're not in a hurry to look at this.

**Comment by clalancette** [comment]
Since we no longer target armhf with ROS 2 releases, I'm going to close this out.  That's not to say we wouldn't accept patches to fix the support, but it is not something the main ROS developers tend to look at, so we don't need an open ticket about it.
