### ISSUE TITLE
rcutils_get_error_string_safe is not available in ROS2 master

### ISSUE THREAD

**Issue by AnandShastry** [ros2/rosbag2#59]
Hi,

rcutils_get_error_string_safe is removed in ROS2 master workspace. It is still being used in rosbag2. 

Below is the error I got while I tried record.

librosbag2_storage.so: undefined symbol: rcutils_get_error_string_safe

**Comment by botteroa-si** [comment]
Hi @AnandShastry,
Yes `rcutils_get_error_string_safe()` has been replaced by `rcutils_get_error_string()`.
We have already replaced it in rosbag2 code. The fix is part of PR #48 (commit 3859622ad3867225a82a19f6fd6d81fe5176603d)
