### ISSUE TITLE
ros2 bag record race condition

### ISSUE THREAD

**Issue by csli8192** [ros2/rosbag2#595]
## Description
- Observed race condition while recording bag files with a 2-machine setup on a local network. It takes multiple polls for rosbag2_transport recorder to discover all the topics. Crashes seems to occur while polling for topics. Sometimes the bag file is corrupted 
- I have not observed it on a single-machine setup
- Applying the fix in https://github.com/csli8192/rosbag2/pull/4 resolves the race conditions issue
  - Modified recorder.cpp to remove the thread used for discovery. The discovery polling is implemented with callbacks. This alone does not solve the problem, but it significantly reduces the number of crashes
  - Used `SQLITE_OPEN_FULLMUTEX` instead of `SQLITE_OPEN_NOMUTEX` in sqlite_wrapper.cpp. I suspect there are some other unsafe multiple threading either in the  writer/sequential_writer or in the SQLite wrapper
- Used Cyclone DDS

### Expected Behavior
- There should be no crashes or corrupted bag files while recording

### Actual Behavior
- crashes sometimes or the bag file is corrupted sometimes when recording

## To Reproduce
1. Setup up multi-machine on a local network
2. Have around ~50 unique topics
3. Run `ros2 bag record <list of all ~50 topics names>` a few times, it fails at least 50% of the time.

## System (please complete the following information)
 - Ubuntu 20.04 docker container
 - Foxy
 - Version: c38630bf5c7bcd9e1e9f46dafe1404d9c76ed938

**Comment by adamdbrw** [comment]
@csli8192 could you confirm that this is resolved with #603?
