### ISSUE TITLE
New release into Rolling

### ISSUE THREAD

**Issue by clalancette** [ros2/rosbag2#615]
rosbag2_cpp is currently failing to build in rolling:

https://build.ros2.org/job/Rbin_uF64__rosbag2_cpp__ubuntu_focal_amd64__binary/81/console

Given the output there, and the fact that it is building on https://ci.ros2.org, I think we probably just need a new release into Rolling.  Would one of the maintainers mind doing that?  Alternatively, I can go ahead and do a release.

Thanks.

**Comment by emersonknapp** [comment]
Noted - I'll take care of this before end of day 1/29. Just wanted to get a few bugfixes merged before doing so

**Comment by clalancette** [comment]
This was done, so closing this out.  Thanks @emersonknapp .
