### ISSUE TITLE
Support zero-copy transport

### ISSUE THREAD

**Issue by albtam** [ros2/rosbag2#652]
## Description

**Edit**

ROS 2 Foxy brought zero-copy APIs to publish and take messages. `rosbag2` should be able to support zero-copy transport.

## How Apex.AI supports zero-copy transport with rosbag2

Since RTI Connext DDS Micro does not provide an API to get the serialized data, our workflow to record and replay messages is different compared to the others DDS implementations. When a message is recorded, the following methods are called: [execute_subscription](https://github.com/ros2/rclcpp/blob/7ccd64c9c1d7b7c4ae996cb114157c3d4211cf3f/rclcpp/src/rclcpp/executor.cpp#L511) -> [rcl_take_serialized_msg](https://github.com/ros2/rclcpp/blob/2531787550084307a5c8144a68c0195fcdd6442a/rclcpp/src/rclcpp/subscription_base.cpp#L166) -> [rmw_take_serialized_message_with_info](https://github.com/ros2/rcl/blob/6d38be606ee3a16bd67b89830029c1201f07933b/rcl/src/rcl/subscription.c#L295)

Until now, this is the same workflow with or without Connext Micro.

What changes in Connext Micro's rmw implementation is that we actually take a non-serialized message (that could be a loaned message) -- by-passing the ROS 2 `take_loaned_message_*` API -- and explicitly serialize the message.

That's the reason why we are already able to use zero-copy. As you might have noticed when I am talking about zero-copy, I don't mean true zero-copy in the sense that the message still needs to be serialized but only the IPC mechanism that can avoid copying the messages to/from SHMEM.

As for the publisher side (rosbag player), the ideal case would be as Karsten explained to "[get] a large enough byte-buffer from the middleware without any further type information". Since this is currently not supported in RTI Connext DDS Micro, we actually borrow a loaned message and fill it with the deserialized message. (see https://github.com/ros2/rosbag2/pull/664) Publishing the message with the existing rosbag2 API (i.e. without borrowing a message) doesn't work because the actual message is [annotated in a way](https://community.rti.com/static/documentation/connext-micro/3.0.3/doc/html/usersmanual/zerocopy.html#getting-started) that forces the user to borrow a loan to publish the message.

## Related PR

https://github.com/ros2/rosbag2/pull/664

## Implementation Notes / Suggestions

After a second thought, I am not sure that what Apex.AI did can be reused as a generic rosbag2. I still opened a PR for reference.

What could make sense in the upstream implementation is:

1. Recording: take a loan message (non serialized), serialize it in rosbag2, and save it on the disk
2. Replay: deserialize the stored message inside the loan message and publish it

**Comment by emersonknapp** [comment]
Is rosbag2 able to successfully record zero-copy messages, though?

Zero copy actually just came up in the working group meeting this morning - I'm not personally that familiar with the feature, but it makes sense that rosbag2 should take advantage of it however possible to help with performance.

If you have a working implementation, a PR against `master` would be very welcome - then we could backport to any other live ros2 distros as necessary, assuming it doesn't break the API/ABI.

**Comment by Karsten1987** [comment]
Happy to review incoming PRs to that topic.

However, I am having trouble following your bug description.
First off, ROS2 started supporting zero-copy messages, that is the concept of `LoanedMessages` starting from Foxy. So I wouldn't expect it to work in `Dashing` as you've mentioned. 
Then further, I don't know what zero-copy means here in terms of replaying a rosbag. You still need to copy the data from the bagfile into a loaned message in that case anyway before you can send them. Given that within the bag the data is only available as a serialized data stream, "loaning a message" from the middleware in this case really only means getting a large enough byte-buffer from the middleware without any further type information. That on the flipside entails that the subscription side should also be able to receive the data as that serialized byte buffer. ROS2 as of now doesn't have the support of loaning serialized messages in their RMW layer, so I feel that problem is a bit bigger than just rosbag2.

Nevertheless, can you elaborate on your reproducer example? I am having a hard time understanding how I can follow your steps.

**Comment by albtam** [comment]
Sure, I'll provide more detail. Just to be clear @Karsten1987 , this is what we discussed at the end of last year (with Apex.AI)

**Comment by albtam** [comment]
I updated the issue description. Can you please update the tag?

> First off, ROS2 started supporting zero-copy messages, that is the concept of LoanedMessages starting from Foxy. So I wouldn't expect it to work in Dashing as you've mentioned.

Our fork is based on Dashing but we backported the ROS 2 Foxy zero-copy APIs. To be more precise, we are by-passing some of the `*take_loaned_message*` APIs.

> I don't know what zero-copy means here in terms of replaying a rosbag. You still need to copy the data from the bagfile into a loaned message in that case anyway before you can send them

By zero-copy, I basically mean the zero-copy transport (which is in this case may not avoid all the copies). Even if on the rosbag2 side some copies might be needed, on the subscriber side, no copy should be required.

> Is rosbag2 able to successfully record zero-copy messages, though?

I haven't tested the "zero-copy" recording for DDS implementations that do provide a `take_serialized` method, but I think that rosbag2 does not support this use-case since as Karsten mentioned "ROS2 as of now doesn't have the support of loaning serialized messages".

**Comment by MichaelOrlov** [comment]
@albtam We need to wrap up with this issue before May 1. \
After May 1 it will be API and new feature freeze for Galactic release.

@Karsten1987  Zero copy in the context of this feature means zero-copy on transport layer. \
Even though we still will need to copy messages and serialize/deserialize them during recording and playback on Rosbag2 side it could give some advantages in total possible data throughput when working locally on embedded devices. 

The real use case could be in recording data from LIDARs and/or cameras on embedded platform locally using IPC without involving transport layer with loopback.

**Comment by albtam** [comment]
Closing the issue because of https://github.com/ros2/rosbag2/pull/664#issuecomment-819020914
