### ISSUE TITLE
Backport performance improvements to Foxy

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#657]
## Description

Discussion overview at https://discourse.ros.org/t/fast-forward-merging-rosbag2-master-api-to-foxy/18927

Summary: major performance improvements on `master` make rosbag2 usable, compared to the Foxy release. This ticket tracks getting the performance improvement onto the Foxy branch (one way or another).

The https://github.com/ros2/rosbag2/tree/foxy-future branch exists with all development up to mid-March 2021, and can be built from source for users who want all improvements

For the default user who installs from APT, however, we want to do the best we can to provide them some of the performance improvements that were discovered.

## Related Issues

* https://github.com/ros2/rosbag2/pull/625
* https://github.com/ros2/rosbag2/issues/435
* #687 

## Completion Criteria

Backport the following PRs, without breaking API/ABI, to Foxy and get it into a sync release. Some may prove difficult and need re-writing on the Foxy branch, this is OK to target a more minimal patch improvement into the stable distro.

* [ ] SQlite config optimized by default https://github.com/ros2/rosbag2/pull/568
* [ ] Double buffering for async writes
  * [ ] feature https://github.com/ros2/rosbag2/pull/546
  * [ ] Thread sync fixes https://github.com/ros2/rosbag2/pull/603 
* [ ] User configuration of SQlite3
  * [ ] https://github.com/ros2/rosbag2/pull/493
  * [ ] https://github.com/ros2/rosbag2/pull/497

## Testing Notes / Suggestions

All existing test suites should run and the build should have no test failures or compiler warnings on the build farm.

**Comment by emersonknapp** [comment]
Updated issue description with a concrete list of PRs to backport

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/fast-forward-merging-rosbag2-master-api-to-foxy/18927/49

**Comment by emersonknapp** [comment]
Closed with `foxy-future` branch
