### ISSUE TITLE
Is there any option available to delete the record after reading it?

### ISSUE THREAD

**Issue by srinivaskernali** [ros2/rosbag2#667]
Hi,

I want delete the record after reading it so that I can avoid increase in the database size. Please let me know if there is any option available for this.

Note: I am using rosbag2 C++ APIs in my code to write and read the sqlite3 db.

**Comment by emersonknapp** [comment]
There is not currently a C++ rosbag2 reader API to delete messages.

**Comment by emersonknapp** [comment]
I'll close this issue as stale for now - but please reopen if you still want to make a feature request and can provide some more information.
