### ISSUE TITLE
Question on how to analyze data using ros2 bag [.db3](3 methods)

### ISSUE THREAD

**Issue by ghdrb9138** [ros2/rosbag2#703]
**## Description**

I want to visualize end-to-end data at once using the bag file (db3) of ros2. So far, I have found three ways.

1. To use various visualization codes used in ros, use SQLite.Switch db3 file to .bag file and apply
2. Visualization method using Python code using .db3 file
3. Convert the .db3 file to csv or txt and plot it => I have limit with UTF-8 convert, what should I do?
4. Is there any additional way? [-s {--storage} way did not work for me. I just want exact way]

**## Related Issues**

 #561

**## Completion Criteria**

Python code or method for visualizing a ros2 bag file

**## Implementation Notes / Suggestions**

I want to see the corresponding end-to-end data as a plot when entering the desired topic (node) in the ros2 bag file. In particular, it would be better if the x and y axis limit were also specified as the maximum minimum. In addition, I would like to see various visualizations through various plots, not just one plot.

**## Testing Notes / Suggestions**

[MANUAL01.zip](https://github.com/ros2/rosbag2/files/6236332/MANUAL01.zip)

**## SYSTEM STATUS**

- Linux : ubuntu 20.04 [Foxy]
- ROS2 [ROS1 is also available on other computers, so anything is only available.]

**Comment by emersonknapp** [comment]
Note to self: This is asking for a Python interface that can read a topic from a bag and produce a 2D plot of the data.

**Comment by facontidavide** [comment]
@ghdrb9138 , Have you tried to used PlotJuggler?

**Comment by GRINGOLOCO7** [comment]
Hi,
I find myself in the same position,
How do I convert my bag (.db3) to a .csv file to see visually the data?
@ghdrb9138 how did you sole this issue?
Thank you

**Comment by nayak2358** [comment]
@facontidavide PlotJuggler works well, thank you! With a lot of recorded topics, it will be great if there is a script to read the ros2 bags and output the csv file in the same format as PlotJuggler does it.

**Comment by facontidavide** [comment]
Using my other package, rox_introspection, it can be done relatively easily.

Someone should implement that... You maybe?

**Comment by nayak2358** [comment]
I don't know enough C++ yet to implement it using your package. So, I found a python API and added some lines to the proposed deserialization script here : https://github.com/ros2/rosbag2/issues/473#issuecomment-2131382174

**Comment by piratax007** [comment]
@nayak2358 The problem with PlotJuggler and Foxglove is that they can't read custom messages.

**Comment by facontidavide** [comment]
not true
PlotJuggler can
