### ISSUE TITLE
Cut new release for rolling & galactic

### ISSUE THREAD

**Issue by Karsten1987** [ros2/rosbag2#758]
In order to make the [buildfarm pass rosbag2_bag_v2](https://build.ros2.org/view/Gbin_uF64/job/Gbin_uF64__rosbag2_bag_v2_plugins__ubuntu_focal_amd64__binary/), we needs a new release for rolling & galactic. 

@emersonknapp I'd propose to cut a new release after we merged https://github.com/ros2/rosbag2/pull/757. Is there anything related to clock which should land before? Obviously, that's not a final galactic release, but we can get things started.

**Comment by emersonknapp** [comment]
I would also like to land https://github.com/ros2/rosbag2/pull/754 before cutting a release

**Comment by emersonknapp** [comment]
@Karsten1987 could use your review on that #754

**Comment by emersonknapp** [comment]
Closing this with
* rolling: https://github.com/ros/rosdistro/pull/29556
* galactic: https://github.com/ros/rosdistro/pull/29555
