### ISSUE TITLE
Add jump/seek API for the Player class

### ISSUE THREAD

**Issue by MichaelOrlov** [ros2/rosbag2#821]
## Description

This feature is part of the #696 
According to the design jump/seek API suppose to allow jump back or forward to an arbitrary point in time during playback. 
During the jump, messages lying in the interval between current timestamp and target time point should not be published.

## Related Issues
- Relates #696 
- Blocked by #813 (will need the same wait)
- Relates #824

## Completion Criteria

1. - [x] jump/seek API able to jump forward to an arbitrary time point during active playback.
2. - [x] jump/seek API able to jump forward to an arbitrary time point when player in pause mode.
3. - [x] jump/seek API able to jump backward to an arbitrary time point during active playback.
4. - [x] jump/seek API able to jump backward to an arbitrary time point when player in pause mode.

## Implementation Notes / Suggestions
We can use the same mechanism for taking over playback as we do in play_next() API, however updating internal message queue is going to be tricky part. 
Also it could be a few nasty race conditions related to the adjustment of the reader position during active playback. Will need to call close-open for reader from separate thread to be able adjust reader position when jumping back in time.

## Testing Notes / Suggestions
Perhaps it would be able to write non-flaky tests using MockReader and MockPlayerClock classes.

**Comment by Kaju-Bubanja** [comment]
Is the seek service currently in master? I see that there is a Seek.srv in rosbag2_interfaces, but when I recompile everything rosbag2 related and resource my workspace and run a bag I don't see the seek service listed when doing ros2 service list.
