### ISSUE TITLE
Bag split updating starting_time metadata field 

### ISSUE THREAD

**Issue by kielczykowski-rai** [ros2/rosbag2#841]
## Description
Recording rosbag with split by duration option updates whole rosbag start timestamp after every split.

### Expected Behavior
Bag splitting doesn't update rosbag start time.

### Actual Behavior
Start time is being updated after every bag split call.

## System
 - **OS**: Ubuntu 20.04
 - **ROS** 2 Distro: Galactic/Rolling (from sources)
 - **Version**: 7407cd7364b7ce1eb2db22e2c3254eefb243f0fe (Rolling)

## To Reproduce
1. Run simple publisher `ros2 run examples_rclcpp_minimal_publisher publisher_not_composable`
2. Run rosbag record with split interval for example 30 s `ros2 bag record -a -d 30`
4. Record bag for multiple split intervals time
5. Check `duration` field in `metadata.yaml` file

## Additional context
Metadata of rosbag shows that whole bag duration equals to split time of bag even if it was being recorded for longer period of time.

Here is example of [metadata.yaml](https://github.com/ros2/rosbag2/files/6945959/metadata.txt) file for rosbag which was recorded for ~ 2.5 min.

Currently I am working on a solution to this issue. PR will be referenced here today or monday.

**Comment by WJaworskiRobotec** [comment]
Additionally I discovered that checks of duration/starting_time are commented out in current tests. Together with fix of this bug we should fix existing tests and add test for recording with splitting by time and replaying the bag (I observed that it doesn't work properly with current master)
