### ISSUE TITLE
missing std_msgs dependency in package.xml and CMakeLists.txt for bag_recorder_nodes

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/rosbag2#868]
In Foxy branch: missing std_msgs dependency in package.xml and CMakeLists.txt for bag_recorder_nodes and needs to be added to the two files accordingly

**Comment by aprotyas** [comment]
Fixed by https://github.com/ros2/rosbag2/pull/861

**Comment by jacobperron** [comment]
The fix has also been released: https://github.com/ros/rosdistro/pull/32041
