### ISSUE TITLE
Deserialize the cdr message without ros environment (C++)

### ISSUE THREAD

**Issue by lowbees** [ros2/rosbag2#898]
I can deserialize the cdr message with ros, but I want run without ros.
How can I do it?

**Comment by emersonknapp** [comment]
For C++, you might try using the https://github.com/eProsima/Fast-CDR library

**Comment by lowbees** [comment]
I have use Fast-CDR library to deserialize the cdr message, but how to get the msg struct like pcl::PointCloud

**Comment by emersonknapp** [comment]
Without using ROS - that will be up to you. You should have fields full of data, which could be translated into other data structures as needed. I'm going to close this as off-topic for rosbag2 specifically. Perhaps this is a better conversation for answers.ros.org (stackoverflow-like) or discourse.ros.org (open discussions)
