### ISSUE TITLE
Could foxy-future branch can pause ros2 bag play

### ISSUE THREAD

**Issue by narutojxl** [ros2/rosbag2#974]
Hello all,
Install foxy by `apt install`, clone rosbag2 source code, checkout foxy-future branch, build OK. So  how could i pause ros2 bag play bag_files with keyboard?  Thanks for your help!

**Comment by emersonknapp** [comment]
Keyboard controls for playback were added in https://github.com/ros2/rosbag2/pull/847 - this feature is only currently available in Rolling (and will be released in Humble)

**Comment by Amazingmum** [comment]
why not update for dashing

**Comment by emersonknapp** [comment]
ROS 2 Dashing has reached end-of-life as of May 21, 2021 and will not be receiving any new features or bugfixes
