### ISSUE TITLE
I can't import rosbag2_py in Ros Foxy

### ISSUE THREAD

**Issue by alvaropascuaI** [ros2/rosbag2#983]
I want to make a python node to be able to record my topics, I have been looking and for example in Ros Galactic they use rosbag2_py to be able to write in a file, then also in Ros Foxy an example but they do it with c++ and I need it in python and I don't I know what else to look at

## System:
 - OS: Ubuntu 20.04
 - ROS 2 Distro: Ros Foxy

**Comment by aprotyas** [comment]
rosbag2_py does not exist in the standard Foxy release but can be accessed in the [`foxy-future` branch](https://github.com/ros2/rosbag2/tree/foxy-future).

**Comment by alvaropascuaI** [comment]
Yes it works thank you very much
