### ISSUE TITLE
receive class loader memory heap warning when using rosbag2_py.SequentialCompressionReader

### ISSUE THREAD

**Issue by benbarron** [ros2/rosbag2#986]
## Description
When I use the SequentialCompressionReader class in the following manner I get the error below. 

```python3 
def readbag(bag_path: str) -> None:
    storage_options = rb2.StorageOptions(
        uri=bag_path, storage_id='sqlite3'
    )
    converter_options = rb2.ConverterOptions(
        input_serialization_format='cdr',
        output_serialization_format='cdr'
    )

    reader = rb2.SequentialCompressionReader()
    reader.open(storage_options, converter_options)

    type_map: Dict[str, Any] = {
        topic.name: topic.type
        for topic in reader.get_all_topics_and_types()
    }

    while reader.has_next():
        (topic, data, t) = reader.read_next()
        msg_type = get_message(type_map[topic])
```

```
Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
         at line 132 in /opt/ros/galactic/src/class_loader/src/class_loader.cpp
```

I have observed this behavior with both zstd compression and my own custom compression plugin. I am not sure if this is a bug or a warning that can just be ignored. If it is a bug I can provide more details on reproducing issue. 

## System 
- Device: nvidia jetson agx - jetpack 4.6.1
 - OS: ubuntu 18.04
 - ROS 2 Distro: galactic
 - Version: release

**Comment by sven-hoek** [comment]
I ran into the same issue. I've been running fine with just ignoring it but a severe warning sounds a lot like there should be some attention paid.

**Comment by emersonknapp** [comment]
I think this was fixed by https://github.com/ros2/rosbag2/pull/1299 and backported to Humble and Iron. Unfortunately Galactic is EOL since November 2022 so its code is final forever. I'll close this as fixed for now, please reopen if there is a remaining issue.

**Comment by sven-hoek** [comment]
I am using Humble and am on the newest package versions and get this issue when playing a compressed bag. Do the current packages have the fix already? (That is the official Ubuntu repos)

**Comment by MichaelOrlov** [comment]
@sven-hoek Sorry we are not able to fix this issue on `Humble` because the fix implies making ABI-breaking changes and we need to keep ABI compatibility for already released ROS2 distros.
See my comment in https://github.com/ros2/rosbag2/pull/1315#issuecomment-1533713940

**Comment by sven-hoek** [comment]
@MichaelOrlov Understandable, thanks for the info. Can I ignore the warning and assume it's only leaked memory that will be cleaned up by the OS after process termination anyway, or are there any other resources that aren't cleaned up correctly?

**Comment by emersonknapp** [comment]
@MichaelOrlov The fix that went into Rolling was to change the declaration order of the member variables so that they were deconstructed in the correct order, right? We may not be able to change the class declaration in Humble, but we do have destructor methods that we can change - maybe https://github.com/ros2/rosbag2/pull/1362 does the trick to backport this fix?

@sven-hoek You are correct that it'll be cleaned up by OS on process termination - but I think we actually can backport a fix as well. I didn't realize that the Humble backport had actually been closed

**Comment by emersonknapp** [comment]
I am going to choose to use https://github.com/ros2/rosbag2/issues/1278 to track ongoing work, lets leave this issue as resolved for Galactic (by way of end-of-life haha)

**Comment by MichaelOrlov** [comment]
@emersonknapp Thank you for suggesting backport with explicit calling for the destructors in the right order.
I overlooked this opportrunity.
