### ISSUE TITLE
I can't do the colcon

### ISSUE THREAD

**Issue by alvaropascuaI** [ros2/rosbag2#991]
I am trying to launch the colcon build --merge-install and it tells me the following error I have launched the **sudo apt install ros-foxy-ament-cmake** command to install it but it still fails me

![image](https://user-images.githubusercontent.com/97975075/163986605-f4e66f75-5572-4c78-b16b-728c2117dcf5.png)

## System
 - OS: Ubuntu Desktop 20.05
 - ROS 2 Distro: foxy
 - Version: branch foxy-future

**Comment by clalancette** [comment]
Did you source `/opt/ros/foxy/setup.bash` before trying to compile?

In general, please ask questions like this over on https://answers.ros.org, which is our central question and answer site.  You are more likely to get a response there.  Closing this out.
